version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@akala/commands"
    versions:
    - 1.0.4
  - dependency-name: "@akala/core"
    versions:
    - 7.0.7
  - dependency-name: "@akala/config"
    versions:
    - 0.0.14
    - 0.0.6
    - 0.0.7
  - dependency-name: html-webpack-plugin
    versions:
    - 5.1.0
    - 5.2.0
  - dependency-name: "@types/yargs"
    versions:
    - 16.0.0
  - dependency-name: sass-loader
    versions:
    - 11.0.1
  registries:
  - npm-registry-registry-npmjs-org
