compressionLevel: mixed

enableGlobalCache: false

enableInlineBuilds: true

enableTelemetry: false

logFilters:
  - level: info

nmMode: hardlinks-local

nodeLinker: node-modules

npmPublishAccess: public

yarnPath: .yarn/releases/yarn-4.9.1.cjs
