import * as globalBitmaps from "./global-Bitmaps.js";
export { globalBitmaps };import * as globalEnums from "./global-Enums.js";
export { globalEnums };import * as globalStructs from "./global-Structs.js";
export { globalStructs };import * as globalTypeDefs from "./global-TypeDefs.js";
export { globalTypeDefs };import * as aCLCluster from "./ACL-Cluster.js";
export { aCLCluster };import * as accountLogin from "./AccountLogin.js";
export { accountLogin };import * as actionsCluster from "./ActionsCluster.js";
export { actionsCluster };import * as adminCommissioningCluster from "./AdminCommissioningCluster.js";
export { adminCommissioningCluster };import * as airQuality from "./AirQuality.js";
export { airQuality };import * as alarmBase from "./AlarmBase.js";
export { alarmBase };import * as applicationBasic from "./ApplicationBasic.js";
export { applicationBasic };import * as applicationLauncher from "./ApplicationLauncher.js";
export { applicationLauncher };import * as audioOutput from "./AudioOutput.js";
export { audioOutput };import * as basicInformationCluster from "./BasicInformationCluster.js";
export { basicInformationCluster };import * as bindingCluster from "./Binding-Cluster.js";
export { bindingCluster };import * as booleanState from "./BooleanState.js";
export { booleanState };import * as booleanStateConfiguration from "./BooleanStateConfiguration.js";
export { booleanStateConfiguration };import * as bridgedDeviceBasicInformationCluster from "./BridgedDeviceBasicInformationCluster.js";
export { bridgedDeviceBasicInformationCluster };import * as cameraAVSettingsUserLevelManagement from "./CameraAVSettingsUserLevelManagement.js";
export { cameraAVSettingsUserLevelManagement };import * as cameraAVStreamManagement from "./CameraAVStreamManagement.js";
export { cameraAVStreamManagement };import * as channel from "./Channel.js";
export { channel };import * as chime from "./Chime.js";
export { chime };import * as closureControl from "./ClosureControl.js";
export { closureControl };import * as closureDimension from "./ClosureDimension.js";
export { closureDimension };import * as colorControl from "./ColorControl.js";
export { colorControl };import * as commissionerControlCluster from "./CommissionerControlCluster.js";
export { commissionerControlCluster };import * as commodityMetering from "./CommodityMetering.js";
export { commodityMetering };import * as commodityPrice from "./CommodityPrice.js";
export { commodityPrice };import * as commodityTariff from "./CommodityTariff.js";
export { commodityTariff };import * as concentrationMeasurement from "./ConcentrationMeasurement.js";
export { concentrationMeasurement };import * as contentAppObserver from "./ContentAppObserver.js";
export { contentAppObserver };import * as contentControl from "./ContentControl.js";
export { contentControl };import * as contentLauncher from "./ContentLauncher.js";
export { contentLauncher };import * as descriptorCluster from "./Descriptor-Cluster.js";
export { descriptorCluster };import * as deviceEnergyManagement from "./DeviceEnergyManagement.js";
export { deviceEnergyManagement };import * as diagnosticLogsCluster from "./DiagnosticLogsCluster.js";
export { diagnosticLogsCluster };import * as diagnosticsEthernet from "./DiagnosticsEthernet.js";
export { diagnosticsEthernet };import * as diagnosticsGeneral from "./DiagnosticsGeneral.js";
export { diagnosticsGeneral };import * as diagnosticsSoftware from "./DiagnosticsSoftware.js";
export { diagnosticsSoftware };import * as diagnosticsThread from "./DiagnosticsThread.js";
export { diagnosticsThread };import * as diagnosticsWiFi from "./DiagnosticsWiFi.js";
export { diagnosticsWiFi };import * as dishwasherAlarm from "./DishwasherAlarm.js";
export { dishwasherAlarm };import * as doorLock from "./DoorLock.js";
export { doorLock };import * as ecosystemInformationCluster from "./EcosystemInformationCluster.js";
export { ecosystemInformationCluster };import * as electricalEnergyMeasurement from "./ElectricalEnergyMeasurement.js";
export { electricalEnergyMeasurement };import * as electricalGridConditions from "./ElectricalGridConditions.js";
export { electricalGridConditions };import * as electricalPowerMeasurement from "./ElectricalPowerMeasurement.js";
export { electricalPowerMeasurement };import * as energyEVSE from "./EnergyEVSE.js";
export { energyEVSE };import * as energyPreference from "./EnergyPreference.js";
export { energyPreference };import * as fanControl from "./FanControl.js";
export { fanControl };import * as fixedLabelCluster from "./FixedLabel-Cluster.js";
export { fixedLabelCluster };import * as flowMeasurement from "./FlowMeasurement.js";
export { flowMeasurement };import * as generalCommissioningCluster from "./GeneralCommissioningCluster.js";
export { generalCommissioningCluster };import * as groupKeyManagementCluster from "./Group-Key-Management-Cluster.js";
export { groupKeyManagementCluster };import * as groups from "./Groups.js";
export { groups };import * as iCDManagement from "./ICDManagement.js";
export { iCDManagement };import * as identify from "./Identify.js";
export { identify };import * as illuminanceMeasurement from "./IlluminanceMeasurement.js";
export { illuminanceMeasurement };import * as jointFabricAdministratorCluster from "./JointFabricAdministratorCluster.js";
export { jointFabricAdministratorCluster };import * as jointFabricDatastoreCluster from "./JointFabricDatastoreCluster.js";
export { jointFabricDatastoreCluster };import * as keypadInput from "./KeypadInput.js";
export { keypadInput };import * as labelCluster from "./Label-Cluster.js";
export { labelCluster };import * as laundryDryerControls from "./LaundryDryerControls.js";
export { laundryDryerControls };import * as laundryWasherControls from "./LaundryWasherControls.js";
export { laundryWasherControls };import * as levelControl from "./LevelControl.js";
export { levelControl };import * as localizationConfiguration from "./LocalizationConfiguration.js";
export { localizationConfiguration };import * as localizationTimeFormat from "./LocalizationTimeFormat.js";
export { localizationTimeFormat };import * as localizationUnit from "./LocalizationUnit.js";
export { localizationUnit };import * as lowPower from "./LowPower.js";
export { lowPower };import * as mediaInput from "./MediaInput.js";
export { mediaInput };import * as mediaPlayback from "./MediaPlayback.js";
export { mediaPlayback };import * as messages from "./Messages.js";
export { messages };import * as meterIdentification from "./MeterIdentification.js";
export { meterIdentification };import * as microwaveOvenControl from "./MicrowaveOvenControl.js";
export { microwaveOvenControl };import * as modeBase from "./ModeBase.js";
export { modeBase };import * as modeSelect from "./ModeSelect.js";
export { modeSelect };import * as modeDeviceEnergyManagement from "./Mode_DeviceEnergyManagement.js";
export { modeDeviceEnergyManagement };import * as modeDishwasher from "./Mode_Dishwasher.js";
export { modeDishwasher };import * as modeEVSE from "./Mode_EVSE.js";
export { modeEVSE };import * as modeLaundryWasher from "./Mode_LaundryWasher.js";
export { modeLaundryWasher };import * as modeMicrowaveOven from "./Mode_MicrowaveOven.js";
export { modeMicrowaveOven };import * as modeOven from "./Mode_Oven.js";
export { modeOven };import * as modeRVCClean from "./Mode_RVCClean.js";
export { modeRVCClean };import * as modeRVCRun from "./Mode_RVCRun.js";
export { modeRVCRun };import * as modeRefrigerator from "./Mode_Refrigerator.js";
export { modeRefrigerator };import * as modeWaterHeater from "./Mode_WaterHeater.js";
export { modeWaterHeater };import * as networkCommissioningCluster from "./NetworkCommissioningCluster.js";
export { networkCommissioningCluster };import * as oTAProvider from "./OTAProvider.js";
export { oTAProvider };import * as oTARequestor from "./OTARequestor.js";
export { oTARequestor };import * as occupancySensing from "./OccupancySensing.js";
export { occupancySensing };import * as onOff from "./OnOff.js";
export { onOff };import * as operationalCredentialCluster from "./OperationalCredentialCluster.js";
export { operationalCredentialCluster };import * as operationalState from "./OperationalState.js";
export { operationalState };import * as operationalStateOven from "./OperationalState_Oven.js";
export { operationalStateOven };import * as operationalStateRVC from "./OperationalState_RVC.js";
export { operationalStateRVC };import * as powerSourceCluster from "./PowerSourceCluster.js";
export { powerSourceCluster };import * as powerSourceConfigurationCluster from "./PowerSourceConfigurationCluster.js";
export { powerSourceConfigurationCluster };import * as powerTopology from "./PowerTopology.js";
export { powerTopology };import * as pressureMeasurement from "./PressureMeasurement.js";
export { pressureMeasurement };import * as pumpConfigurationControl from "./PumpConfigurationControl.js";
export { pumpConfigurationControl };import * as pushAVStreamTransport from "./PushAVStreamTransport.js";
export { pushAVStreamTransport };import * as refrigeratorAlarm from "./RefrigeratorAlarm.js";
export { refrigeratorAlarm };import * as resourceMonitoring from "./ResourceMonitoring.js";
export { resourceMonitoring };import * as scenes from "./Scenes.js";
export { scenes };import * as serviceArea from "./ServiceArea.js";
export { serviceArea };import * as smokeCOAlarm from "./SmokeCOAlarm.js";
export { smokeCOAlarm };import * as soilMeasurement from "./SoilMeasurement.js";
export { soilMeasurement };import * as switch_ from "./Switch.js";
export { switch_ };import * as tLSCertificateManagement from "./TLSCertificateManagement.js";
export { tLSCertificateManagement };import * as tLSClientManagement from "./TLSClientManagement.js";
export { tLSClientManagement };import * as targetNavigator from "./TargetNavigator.js";
export { targetNavigator };import * as temperatureControl from "./TemperatureControl.js";
export { temperatureControl };import * as temperatureMeasurement from "./TemperatureMeasurement.js";
export { temperatureMeasurement };import * as thermostat from "./Thermostat.js";
export { thermostat };import * as thermostatUserInterfaceConfiguration from "./ThermostatUserInterfaceConfiguration.js";
export { thermostatUserInterfaceConfiguration };import * as threadBorderRouterManagement from "./ThreadBorderRouterManagement.js";
export { threadBorderRouterManagement };import * as threadNetworkDirectory from "./ThreadNetworkDirectory.js";
export { threadNetworkDirectory };import * as timeSync from "./TimeSync.js";
export { timeSync };import * as userLabelCluster from "./UserLabel-Cluster.js";
export { userLabelCluster };import * as valveConfigurationControl from "./ValveConfigurationControl.js";
export { valveConfigurationControl };import * as wakeOnLAN from "./WakeOnLAN.js";
export { wakeOnLAN };import * as waterContentMeasurement from "./WaterContentMeasurement.js";
export { waterContentMeasurement };import * as waterHeaterManagement from "./WaterHeaterManagement.js";
export { waterHeaterManagement };import * as webRTCProvider from "./WebRTC_Provider.js";
export { webRTCProvider };import * as webRTCRequestor from "./WebRTC_Requestor.js";
export { webRTCRequestor };import * as wiFiNetworkManagement from "./WiFiNetworkManagement.js";
export { wiFiNetworkManagement };import * as windowCovering from "./WindowCovering.js";
export { windowCovering };import * as zoneManagement from "./ZoneManagement.js";
export { zoneManagement };

export enum ClusterIds {
	AccessControl = 31,
	AccountLogin = 1294,
	Actions = 37,
	AdministratorCommissioning = 60,
	AirQuality = 91,
	ApplicationBasic = 1293,
	ApplicationLauncher = 1292,
	AudioOutput = 1291,
	BasicInformation = 40,
	Binding = 30,
	BooleanState = 69,
	BooleanStateConfiguration = 128,
	BridgedDeviceBasicInformation = 57,
	CameraAVSettingsUserLevelManagement = 1362,
	CameraAVStreamManagement = 1361,
	Channel = 1284,
	Chime = 1366,
	ClosureControl = 260,
	ClosureDimension = 261,
	ColorControl = 768,
	CommissionerControl = 1873,
	CommodityMetering = 2823,
	CommodityPrice = 149,
	CommodityTariff = 1792,
	CarbonMonoxideConcentrationMeasurement = 1036,
	CarbonDioxideConcentrationMeasurement = 1037,
	NitrogenDioxideConcentrationMeasurement = 1043,
	OzoneConcentrationMeasurement = 1045,
	PM2_5ConcentrationMeasurement = 1066,
	FormaldehydeConcentrationMeasurement = 1067,
	PM1ConcentrationMeasurement = 1068,
	PM10ConcentrationMeasurement = 1069,
	TotalVolatileOrganicCompoundsConcentrationMeasurement = 1070,
	RadonConcentrationMeasurement = 1071,
	ContentAppObserver = 1296,
	ContentControl = 1295,
	ContentLauncher = 1290,
	Descriptor = 29,
	DeviceEnergyManagement = 152,
	DiagnosticLogs = 50,
	EthernetNetworkDiagnostics = 55,
	GeneralDiagnostics = 51,
	SoftwareDiagnostics = 52,
	ThreadNetworkDiagnostics = 53,
	WiFiNetworkDiagnostics = 54,
	DishwasherAlarm = 93,
	DoorLock = 257,
	EcosystemInformation = 1872,
	ElectricalEnergyMeasurement = 145,
	ElectricalGridConditions = 160,
	ElectricalPowerMeasurement = 144,
	EnergyEVSE = 153,
	EnergyPreference = 155,
	FanControl = 514,
	FixedLabel = 64,
	FlowMeasurement = 1028,
	GeneralCommissioning = 48,
	GroupKeyManagement = 63,
	Groups = 4,
	ICDManagement = 70,
	Identify = 3,
	IlluminanceMeasurement = 1024,
	JointFabricAdministrator = 1875,
	JointFabricDatastore = 1874,
	KeypadInput = 1289,
	LaundryDryerControls = 74,
	LaundryWasherControls = 83,
	LevelControl = 8,
	LocalizationConfiguration = 43,
	TimeFormatLocalization = 44,
	UnitLocalization = 45,
	LowPower = 1288,
	MediaInput = 1287,
	MediaPlayback = 1286,
	Messages = 151,
	MeterIdentification = 2822,
	MicrowaveOvenControl = 95,
	ModeSelect = 80,
	DeviceEnergyManagementMode = 159,
	DishwasherMode = 89,
	EnergyEVSEMode = 157,
	LaundryWasherMode = 81,
	MicrowaveOvenMode = 94,
	OvenMode = 73,
	RVCCleanMode = 85,
	RVCRunMode = 84,
	RefrigeratorAndTemperatureControlledCabinetMode = 82,
	WaterHeaterMode = 158,
	NetworkCommissioning = 49,
	OTASoftwareUpdateProvider = 41,
	OTASoftwareUpdateRequestor = 42,
	OccupancySensing = 1030,
	OnOff = 6,
	OperationalCredentials = 62,
	OperationalState = 96,
	OvenCavityOperationalState = 72,
	RVCOperationalState = 97,
	PowerSource = 47,
	PowerSourceConfiguration = 46,
	PowerTopology = 156,
	PressureMeasurement = 1027,
	PumpConfigurationAndControl = 512,
	PushAVStreamTransport = 1365,
	RefrigeratorAlarm = 87,
	HEPAFilterMonitoring = 113,
	ActivatedCarbonFilterMonitoring = 114,
	WaterTankLevelMonitoring = 121,
	ScenesManagement = 98,
	ServiceArea = 336,
	SmokeCOAlarm = 92,
	SoilMeasurement = 1072,
	Switch = 59,
	TLSCertificateManagement = 2049,
	TLSClientManagement = 2050,
	TargetNavigator = 1285,
	TemperatureControl = 86,
	TemperatureMeasurement = 1026,
	Thermostat = 513,
	ThermostatUserInterfaceConfiguration = 516,
	ThreadBorderRouterManagement = 1106,
	ThreadNetworkDirectory = 1107,
	TimeSynchronization = 56,
	UserLabel = 65,
	ValveConfigurationAndControl = 129,
	WakeOnLAN = 1283,
	RelativeHumidityMeasurement = 1029,
	WaterHeaterManagement = 148,
	WebRTCTransportProvider = 1363,
	WebRTCTransportRequestor = 1364,
	WiFiNetworkManagement = 1105,
	WindowCovering = 258,
	ZoneManagement = 1360,
}

export type ClusterIdMap = {
	[ClusterIds.AccessControl]: aCLCluster.AccessControl,
	[ClusterIds.AccountLogin]: accountLogin.AccountLogin,
	[ClusterIds.Actions]: actionsCluster.Actions,
	[ClusterIds.AdministratorCommissioning]: adminCommissioningCluster.AdministratorCommissioning,
	[ClusterIds.AirQuality]: airQuality.AirQuality,
	[ClusterIds.ApplicationBasic]: applicationBasic.ApplicationBasic,
	[ClusterIds.ApplicationLauncher]: applicationLauncher.ApplicationLauncher,
	[ClusterIds.AudioOutput]: audioOutput.AudioOutput,
	[ClusterIds.BasicInformation]: basicInformationCluster.BasicInformation,
	[ClusterIds.Binding]: bindingCluster.Binding,
	[ClusterIds.BooleanState]: booleanState.BooleanState,
	[ClusterIds.BooleanStateConfiguration]: booleanStateConfiguration.BooleanStateConfiguration,
	[ClusterIds.BridgedDeviceBasicInformation]: bridgedDeviceBasicInformationCluster.BridgedDeviceBasicInformation,
	[ClusterIds.CameraAVSettingsUserLevelManagement]: cameraAVSettingsUserLevelManagement.CameraAVSettingsUserLevelManagement,
	[ClusterIds.CameraAVStreamManagement]: cameraAVStreamManagement.CameraAVStreamManagement,
	[ClusterIds.Channel]: channel.Channel,
	[ClusterIds.Chime]: chime.Chime,
	[ClusterIds.ClosureControl]: closureControl.ClosureControl,
	[ClusterIds.ClosureDimension]: closureDimension.ClosureDimension,
	[ClusterIds.ColorControl]: colorControl.ColorControl,
	[ClusterIds.CommissionerControl]: commissionerControlCluster.CommissionerControl,
	[ClusterIds.CommodityMetering]: commodityMetering.CommodityMetering,
	[ClusterIds.CommodityPrice]: commodityPrice.CommodityPrice,
	[ClusterIds.CommodityTariff]: commodityTariff.CommodityTariff,
	[ClusterIds.CarbonMonoxideConcentrationMeasurement]: concentrationMeasurement.CarbonMonoxideConcentrationMeasurement,
	[ClusterIds.CarbonDioxideConcentrationMeasurement]: concentrationMeasurement.CarbonDioxideConcentrationMeasurement,
	[ClusterIds.NitrogenDioxideConcentrationMeasurement]: concentrationMeasurement.NitrogenDioxideConcentrationMeasurement,
	[ClusterIds.OzoneConcentrationMeasurement]: concentrationMeasurement.OzoneConcentrationMeasurement,
	[ClusterIds.PM2_5ConcentrationMeasurement]: concentrationMeasurement.PM2_5ConcentrationMeasurement,
	[ClusterIds.FormaldehydeConcentrationMeasurement]: concentrationMeasurement.FormaldehydeConcentrationMeasurement,
	[ClusterIds.PM1ConcentrationMeasurement]: concentrationMeasurement.PM1ConcentrationMeasurement,
	[ClusterIds.PM10ConcentrationMeasurement]: concentrationMeasurement.PM10ConcentrationMeasurement,
	[ClusterIds.TotalVolatileOrganicCompoundsConcentrationMeasurement]: concentrationMeasurement.TotalVolatileOrganicCompoundsConcentrationMeasurement,
	[ClusterIds.RadonConcentrationMeasurement]: concentrationMeasurement.RadonConcentrationMeasurement,
	[ClusterIds.ContentAppObserver]: contentAppObserver.ContentAppObserver,
	[ClusterIds.ContentControl]: contentControl.ContentControl,
	[ClusterIds.ContentLauncher]: contentLauncher.ContentLauncher,
	[ClusterIds.Descriptor]: descriptorCluster.Descriptor,
	[ClusterIds.DeviceEnergyManagement]: deviceEnergyManagement.DeviceEnergyManagement,
	[ClusterIds.DiagnosticLogs]: diagnosticLogsCluster.DiagnosticLogs,
	[ClusterIds.EthernetNetworkDiagnostics]: diagnosticsEthernet.EthernetNetworkDiagnostics,
	[ClusterIds.GeneralDiagnostics]: diagnosticsGeneral.GeneralDiagnostics,
	[ClusterIds.SoftwareDiagnostics]: diagnosticsSoftware.SoftwareDiagnostics,
	[ClusterIds.ThreadNetworkDiagnostics]: diagnosticsThread.ThreadNetworkDiagnostics,
	[ClusterIds.WiFiNetworkDiagnostics]: diagnosticsWiFi.WiFiNetworkDiagnostics,
	[ClusterIds.DishwasherAlarm]: dishwasherAlarm.DishwasherAlarm,
	[ClusterIds.DoorLock]: doorLock.DoorLock,
	[ClusterIds.EcosystemInformation]: ecosystemInformationCluster.EcosystemInformation,
	[ClusterIds.ElectricalEnergyMeasurement]: electricalEnergyMeasurement.ElectricalEnergyMeasurement,
	[ClusterIds.ElectricalGridConditions]: electricalGridConditions.ElectricalGridConditions,
	[ClusterIds.ElectricalPowerMeasurement]: electricalPowerMeasurement.ElectricalPowerMeasurement,
	[ClusterIds.EnergyEVSE]: energyEVSE.EnergyEVSE,
	[ClusterIds.EnergyPreference]: energyPreference.EnergyPreference,
	[ClusterIds.FanControl]: fanControl.FanControl,
	[ClusterIds.FixedLabel]: fixedLabelCluster.FixedLabel,
	[ClusterIds.FlowMeasurement]: flowMeasurement.FlowMeasurement,
	[ClusterIds.GeneralCommissioning]: generalCommissioningCluster.GeneralCommissioning,
	[ClusterIds.GroupKeyManagement]: groupKeyManagementCluster.GroupKeyManagement,
	[ClusterIds.Groups]: groups.Groups,
	[ClusterIds.ICDManagement]: iCDManagement.ICDManagement,
	[ClusterIds.Identify]: identify.Identify,
	[ClusterIds.IlluminanceMeasurement]: illuminanceMeasurement.IlluminanceMeasurement,
	[ClusterIds.JointFabricAdministrator]: jointFabricAdministratorCluster.JointFabricAdministrator,
	[ClusterIds.JointFabricDatastore]: jointFabricDatastoreCluster.JointFabricDatastore,
	[ClusterIds.KeypadInput]: keypadInput.KeypadInput,
	[ClusterIds.LaundryDryerControls]: laundryDryerControls.LaundryDryerControls,
	[ClusterIds.LaundryWasherControls]: laundryWasherControls.LaundryWasherControls,
	[ClusterIds.LevelControl]: levelControl.LevelControl,
	[ClusterIds.LocalizationConfiguration]: localizationConfiguration.LocalizationConfiguration,
	[ClusterIds.TimeFormatLocalization]: localizationTimeFormat.TimeFormatLocalization,
	[ClusterIds.UnitLocalization]: localizationUnit.UnitLocalization,
	[ClusterIds.LowPower]: lowPower.LowPower,
	[ClusterIds.MediaInput]: mediaInput.MediaInput,
	[ClusterIds.MediaPlayback]: mediaPlayback.MediaPlayback,
	[ClusterIds.Messages]: messages.Messages,
	[ClusterIds.MeterIdentification]: meterIdentification.MeterIdentification,
	[ClusterIds.MicrowaveOvenControl]: microwaveOvenControl.MicrowaveOvenControl,
	[ClusterIds.ModeSelect]: modeSelect.ModeSelect,
	[ClusterIds.DeviceEnergyManagementMode]: modeDeviceEnergyManagement.DeviceEnergyManagementMode,
	[ClusterIds.DishwasherMode]: modeDishwasher.DishwasherMode,
	[ClusterIds.EnergyEVSEMode]: modeEVSE.EnergyEVSEMode,
	[ClusterIds.LaundryWasherMode]: modeLaundryWasher.LaundryWasherMode,
	[ClusterIds.MicrowaveOvenMode]: modeMicrowaveOven.MicrowaveOvenMode,
	[ClusterIds.OvenMode]: modeOven.OvenMode,
	[ClusterIds.RVCCleanMode]: modeRVCClean.RVCCleanMode,
	[ClusterIds.RVCRunMode]: modeRVCRun.RVCRunMode,
	[ClusterIds.RefrigeratorAndTemperatureControlledCabinetMode]: modeRefrigerator.RefrigeratorAndTemperatureControlledCabinetMode,
	[ClusterIds.WaterHeaterMode]: modeWaterHeater.WaterHeaterMode,
	[ClusterIds.NetworkCommissioning]: networkCommissioningCluster.NetworkCommissioning,
	[ClusterIds.OTASoftwareUpdateProvider]: oTAProvider.OTASoftwareUpdateProvider,
	[ClusterIds.OTASoftwareUpdateRequestor]: oTARequestor.OTASoftwareUpdateRequestor,
	[ClusterIds.OccupancySensing]: occupancySensing.OccupancySensing,
	[ClusterIds.OnOff]: onOff.OnOff,
	[ClusterIds.OperationalCredentials]: operationalCredentialCluster.OperationalCredentials,
	[ClusterIds.OperationalState]: operationalState.OperationalState,
	[ClusterIds.OvenCavityOperationalState]: operationalStateOven.OvenCavityOperationalState,
	[ClusterIds.RVCOperationalState]: operationalStateRVC.RVCOperationalState,
	[ClusterIds.PowerSource]: powerSourceCluster.PowerSource,
	[ClusterIds.PowerSourceConfiguration]: powerSourceConfigurationCluster.PowerSourceConfiguration,
	[ClusterIds.PowerTopology]: powerTopology.PowerTopology,
	[ClusterIds.PressureMeasurement]: pressureMeasurement.PressureMeasurement,
	[ClusterIds.PumpConfigurationAndControl]: pumpConfigurationControl.PumpConfigurationAndControl,
	[ClusterIds.PushAVStreamTransport]: pushAVStreamTransport.PushAVStreamTransport,
	[ClusterIds.RefrigeratorAlarm]: refrigeratorAlarm.RefrigeratorAlarm,
	[ClusterIds.HEPAFilterMonitoring]: resourceMonitoring.HEPAFilterMonitoring,
	[ClusterIds.ActivatedCarbonFilterMonitoring]: resourceMonitoring.ActivatedCarbonFilterMonitoring,
	[ClusterIds.WaterTankLevelMonitoring]: resourceMonitoring.WaterTankLevelMonitoring,
	[ClusterIds.ScenesManagement]: scenes.ScenesManagement,
	[ClusterIds.ServiceArea]: serviceArea.ServiceArea,
	[ClusterIds.SmokeCOAlarm]: smokeCOAlarm.SmokeCOAlarm,
	[ClusterIds.SoilMeasurement]: soilMeasurement.SoilMeasurement,
	[ClusterIds.Switch]: switch_.Switch,
	[ClusterIds.TLSCertificateManagement]: tLSCertificateManagement.TLSCertificateManagement,
	[ClusterIds.TLSClientManagement]: tLSClientManagement.TLSClientManagement,
	[ClusterIds.TargetNavigator]: targetNavigator.TargetNavigator,
	[ClusterIds.TemperatureControl]: temperatureControl.TemperatureControl,
	[ClusterIds.TemperatureMeasurement]: temperatureMeasurement.TemperatureMeasurement,
	[ClusterIds.Thermostat]: thermostat.Thermostat,
	[ClusterIds.ThermostatUserInterfaceConfiguration]: thermostatUserInterfaceConfiguration.ThermostatUserInterfaceConfiguration,
	[ClusterIds.ThreadBorderRouterManagement]: threadBorderRouterManagement.ThreadBorderRouterManagement,
	[ClusterIds.ThreadNetworkDirectory]: threadNetworkDirectory.ThreadNetworkDirectory,
	[ClusterIds.TimeSynchronization]: timeSync.TimeSynchronization,
	[ClusterIds.UserLabel]: userLabelCluster.UserLabel,
	[ClusterIds.ValveConfigurationAndControl]: valveConfigurationControl.ValveConfigurationAndControl,
	[ClusterIds.WakeOnLAN]: wakeOnLAN.WakeOnLAN,
	[ClusterIds.RelativeHumidityMeasurement]: waterContentMeasurement.RelativeHumidityMeasurement,
	[ClusterIds.WaterHeaterManagement]: waterHeaterManagement.WaterHeaterManagement,
	[ClusterIds.WebRTCTransportProvider]: webRTCProvider.WebRTCTransportProvider,
	[ClusterIds.WebRTCTransportRequestor]: webRTCRequestor.WebRTCTransportRequestor,
	[ClusterIds.WiFiNetworkManagement]: wiFiNetworkManagement.WiFiNetworkManagement,
	[ClusterIds.WindowCovering]: windowCovering.WindowCovering,
	[ClusterIds.ZoneManagement]: zoneManagement.ZoneManagement,
}

export type ClusterMap = {
	accessControl: aCLCluster.AccessControl,
	accountLogin: accountLogin.AccountLogin,
	actions: actionsCluster.Actions,
	administratorCommissioning: adminCommissioningCluster.AdministratorCommissioning,
	airQuality: airQuality.AirQuality,
	applicationBasic: applicationBasic.ApplicationBasic,
	applicationLauncher: applicationLauncher.ApplicationLauncher,
	audioOutput: audioOutput.AudioOutput,
	basicInformation: basicInformationCluster.BasicInformation,
	binding: bindingCluster.Binding,
	booleanState: booleanState.BooleanState,
	booleanStateConfiguration: booleanStateConfiguration.BooleanStateConfiguration,
	bridgedDeviceBasicInformation: bridgedDeviceBasicInformationCluster.BridgedDeviceBasicInformation,
	cameraAVSettingsUserLevelManagement: cameraAVSettingsUserLevelManagement.CameraAVSettingsUserLevelManagement,
	cameraAVStreamManagement: cameraAVStreamManagement.CameraAVStreamManagement,
	channel: channel.Channel,
	chime: chime.Chime,
	closureControl: closureControl.ClosureControl,
	closureDimension: closureDimension.ClosureDimension,
	colorControl: colorControl.ColorControl,
	commissionerControl: commissionerControlCluster.CommissionerControl,
	commodityMetering: commodityMetering.CommodityMetering,
	commodityPrice: commodityPrice.CommodityPrice,
	commodityTariff: commodityTariff.CommodityTariff,
	carbonMonoxideConcentrationMeasurement: concentrationMeasurement.CarbonMonoxideConcentrationMeasurement,
	carbonDioxideConcentrationMeasurement: concentrationMeasurement.CarbonDioxideConcentrationMeasurement,
	nitrogenDioxideConcentrationMeasurement: concentrationMeasurement.NitrogenDioxideConcentrationMeasurement,
	ozoneConcentrationMeasurement: concentrationMeasurement.OzoneConcentrationMeasurement,
	pM2_5ConcentrationMeasurement: concentrationMeasurement.PM2_5ConcentrationMeasurement,
	formaldehydeConcentrationMeasurement: concentrationMeasurement.FormaldehydeConcentrationMeasurement,
	pM1ConcentrationMeasurement: concentrationMeasurement.PM1ConcentrationMeasurement,
	pM10ConcentrationMeasurement: concentrationMeasurement.PM10ConcentrationMeasurement,
	totalVolatileOrganicCompoundsConcentrationMeasurement: concentrationMeasurement.TotalVolatileOrganicCompoundsConcentrationMeasurement,
	radonConcentrationMeasurement: concentrationMeasurement.RadonConcentrationMeasurement,
	contentAppObserver: contentAppObserver.ContentAppObserver,
	contentControl: contentControl.ContentControl,
	contentLauncher: contentLauncher.ContentLauncher,
	descriptor: descriptorCluster.Descriptor,
	deviceEnergyManagement: deviceEnergyManagement.DeviceEnergyManagement,
	diagnosticLogs: diagnosticLogsCluster.DiagnosticLogs,
	ethernetNetworkDiagnostics: diagnosticsEthernet.EthernetNetworkDiagnostics,
	generalDiagnostics: diagnosticsGeneral.GeneralDiagnostics,
	softwareDiagnostics: diagnosticsSoftware.SoftwareDiagnostics,
	threadNetworkDiagnostics: diagnosticsThread.ThreadNetworkDiagnostics,
	wiFiNetworkDiagnostics: diagnosticsWiFi.WiFiNetworkDiagnostics,
	dishwasherAlarm: dishwasherAlarm.DishwasherAlarm,
	doorLock: doorLock.DoorLock,
	ecosystemInformation: ecosystemInformationCluster.EcosystemInformation,
	electricalEnergyMeasurement: electricalEnergyMeasurement.ElectricalEnergyMeasurement,
	electricalGridConditions: electricalGridConditions.ElectricalGridConditions,
	electricalPowerMeasurement: electricalPowerMeasurement.ElectricalPowerMeasurement,
	energyEVSE: energyEVSE.EnergyEVSE,
	energyPreference: energyPreference.EnergyPreference,
	fanControl: fanControl.FanControl,
	fixedLabel: fixedLabelCluster.FixedLabel,
	flowMeasurement: flowMeasurement.FlowMeasurement,
	generalCommissioning: generalCommissioningCluster.GeneralCommissioning,
	groupKeyManagement: groupKeyManagementCluster.GroupKeyManagement,
	groups: groups.Groups,
	iCDManagement: iCDManagement.ICDManagement,
	identify: identify.Identify,
	illuminanceMeasurement: illuminanceMeasurement.IlluminanceMeasurement,
	jointFabricAdministrator: jointFabricAdministratorCluster.JointFabricAdministrator,
	jointFabricDatastore: jointFabricDatastoreCluster.JointFabricDatastore,
	keypadInput: keypadInput.KeypadInput,
	laundryDryerControls: laundryDryerControls.LaundryDryerControls,
	laundryWasherControls: laundryWasherControls.LaundryWasherControls,
	levelControl: levelControl.LevelControl,
	localizationConfiguration: localizationConfiguration.LocalizationConfiguration,
	timeFormatLocalization: localizationTimeFormat.TimeFormatLocalization,
	unitLocalization: localizationUnit.UnitLocalization,
	lowPower: lowPower.LowPower,
	mediaInput: mediaInput.MediaInput,
	mediaPlayback: mediaPlayback.MediaPlayback,
	messages: messages.Messages,
	meterIdentification: meterIdentification.MeterIdentification,
	microwaveOvenControl: microwaveOvenControl.MicrowaveOvenControl,
	modeSelect: modeSelect.ModeSelect,
	deviceEnergyManagementMode: modeDeviceEnergyManagement.DeviceEnergyManagementMode,
	dishwasherMode: modeDishwasher.DishwasherMode,
	energyEVSEMode: modeEVSE.EnergyEVSEMode,
	laundryWasherMode: modeLaundryWasher.LaundryWasherMode,
	microwaveOvenMode: modeMicrowaveOven.MicrowaveOvenMode,
	ovenMode: modeOven.OvenMode,
	rVCCleanMode: modeRVCClean.RVCCleanMode,
	rVCRunMode: modeRVCRun.RVCRunMode,
	refrigeratorAndTemperatureControlledCabinetMode: modeRefrigerator.RefrigeratorAndTemperatureControlledCabinetMode,
	waterHeaterMode: modeWaterHeater.WaterHeaterMode,
	networkCommissioning: networkCommissioningCluster.NetworkCommissioning,
	oTASoftwareUpdateProvider: oTAProvider.OTASoftwareUpdateProvider,
	oTASoftwareUpdateRequestor: oTARequestor.OTASoftwareUpdateRequestor,
	occupancySensing: occupancySensing.OccupancySensing,
	onOff: onOff.OnOff,
	operationalCredentials: operationalCredentialCluster.OperationalCredentials,
	operationalState: operationalState.OperationalState,
	ovenCavityOperationalState: operationalStateOven.OvenCavityOperationalState,
	rVCOperationalState: operationalStateRVC.RVCOperationalState,
	powerSource: powerSourceCluster.PowerSource,
	powerSourceConfiguration: powerSourceConfigurationCluster.PowerSourceConfiguration,
	powerTopology: powerTopology.PowerTopology,
	pressureMeasurement: pressureMeasurement.PressureMeasurement,
	pumpConfigurationAndControl: pumpConfigurationControl.PumpConfigurationAndControl,
	pushAVStreamTransport: pushAVStreamTransport.PushAVStreamTransport,
	refrigeratorAlarm: refrigeratorAlarm.RefrigeratorAlarm,
	hEPAFilterMonitoring: resourceMonitoring.HEPAFilterMonitoring,
	activatedCarbonFilterMonitoring: resourceMonitoring.ActivatedCarbonFilterMonitoring,
	waterTankLevelMonitoring: resourceMonitoring.WaterTankLevelMonitoring,
	scenesManagement: scenes.ScenesManagement,
	serviceArea: serviceArea.ServiceArea,
	smokeCOAlarm: smokeCOAlarm.SmokeCOAlarm,
	soilMeasurement: soilMeasurement.SoilMeasurement,
	switch_: switch_.Switch,
	tLSCertificateManagement: tLSCertificateManagement.TLSCertificateManagement,
	tLSClientManagement: tLSClientManagement.TLSClientManagement,
	targetNavigator: targetNavigator.TargetNavigator,
	temperatureControl: temperatureControl.TemperatureControl,
	temperatureMeasurement: temperatureMeasurement.TemperatureMeasurement,
	thermostat: thermostat.Thermostat,
	thermostatUserInterfaceConfiguration: thermostatUserInterfaceConfiguration.ThermostatUserInterfaceConfiguration,
	threadBorderRouterManagement: threadBorderRouterManagement.ThreadBorderRouterManagement,
	threadNetworkDirectory: threadNetworkDirectory.ThreadNetworkDirectory,
	timeSynchronization: timeSync.TimeSynchronization,
	userLabel: userLabelCluster.UserLabel,
	valveConfigurationAndControl: valveConfigurationControl.ValveConfigurationAndControl,
	wakeOnLAN: wakeOnLAN.WakeOnLAN,
	relativeHumidityMeasurement: waterContentMeasurement.RelativeHumidityMeasurement,
	waterHeaterManagement: waterHeaterManagement.WaterHeaterManagement,
	webRTCTransportProvider: webRTCProvider.WebRTCTransportProvider,
	webRTCTransportRequestor: webRTCRequestor.WebRTCTransportRequestor,
	wiFiNetworkManagement: wiFiNetworkManagement.WiFiNetworkManagement,
	windowCovering: windowCovering.WindowCovering,
	zoneManagement: zoneManagement.ZoneManagement,
}

export const ClusterMap = {
	[31]: aCLCluster.accessControl,
	[1294]: accountLogin.accountLogin,
	[37]: actionsCluster.actions,
	[60]: adminCommissioningCluster.administratorCommissioning,
	[91]: airQuality.airQuality,
	[1293]: applicationBasic.applicationBasic,
	[1292]: applicationLauncher.applicationLauncher,
	[1291]: audioOutput.audioOutput,
	[40]: basicInformationCluster.basicInformation,
	[30]: bindingCluster.binding,
	[69]: booleanState.booleanState,
	[128]: booleanStateConfiguration.booleanStateConfiguration,
	[57]: bridgedDeviceBasicInformationCluster.bridgedDeviceBasicInformation,
	[1362]: cameraAVSettingsUserLevelManagement.cameraAVSettingsUserLevelManagement,
	[1361]: cameraAVStreamManagement.cameraAVStreamManagement,
	[1284]: channel.channel,
	[1366]: chime.chime,
	[260]: closureControl.closureControl,
	[261]: closureDimension.closureDimension,
	[768]: colorControl.colorControl,
	[1873]: commissionerControlCluster.commissionerControl,
	[2823]: commodityMetering.commodityMetering,
	[149]: commodityPrice.commodityPrice,
	[1792]: commodityTariff.commodityTariff,
	[1036]: concentrationMeasurement.carbonMonoxideConcentrationMeasurement,
	[1037]: concentrationMeasurement.carbonDioxideConcentrationMeasurement,
	[1043]: concentrationMeasurement.nitrogenDioxideConcentrationMeasurement,
	[1045]: concentrationMeasurement.ozoneConcentrationMeasurement,
	[1066]: concentrationMeasurement.pM2_5ConcentrationMeasurement,
	[1067]: concentrationMeasurement.formaldehydeConcentrationMeasurement,
	[1068]: concentrationMeasurement.pM1ConcentrationMeasurement,
	[1069]: concentrationMeasurement.pM10ConcentrationMeasurement,
	[1070]: concentrationMeasurement.totalVolatileOrganicCompoundsConcentrationMeasurement,
	[1071]: concentrationMeasurement.radonConcentrationMeasurement,
	[1296]: contentAppObserver.contentAppObserver,
	[1295]: contentControl.contentControl,
	[1290]: contentLauncher.contentLauncher,
	[29]: descriptorCluster.descriptor,
	[152]: deviceEnergyManagement.deviceEnergyManagement,
	[50]: diagnosticLogsCluster.diagnosticLogs,
	[55]: diagnosticsEthernet.ethernetNetworkDiagnostics,
	[51]: diagnosticsGeneral.generalDiagnostics,
	[52]: diagnosticsSoftware.softwareDiagnostics,
	[53]: diagnosticsThread.threadNetworkDiagnostics,
	[54]: diagnosticsWiFi.wiFiNetworkDiagnostics,
	[93]: dishwasherAlarm.dishwasherAlarm,
	[257]: doorLock.doorLock,
	[1872]: ecosystemInformationCluster.ecosystemInformation,
	[145]: electricalEnergyMeasurement.electricalEnergyMeasurement,
	[160]: electricalGridConditions.electricalGridConditions,
	[144]: electricalPowerMeasurement.electricalPowerMeasurement,
	[153]: energyEVSE.energyEVSE,
	[155]: energyPreference.energyPreference,
	[514]: fanControl.fanControl,
	[64]: fixedLabelCluster.fixedLabel,
	[1028]: flowMeasurement.flowMeasurement,
	[48]: generalCommissioningCluster.generalCommissioning,
	[63]: groupKeyManagementCluster.groupKeyManagement,
	[4]: groups.groups,
	[70]: iCDManagement.iCDManagement,
	[3]: identify.identify,
	[1024]: illuminanceMeasurement.illuminanceMeasurement,
	[1875]: jointFabricAdministratorCluster.jointFabricAdministrator,
	[1874]: jointFabricDatastoreCluster.jointFabricDatastore,
	[1289]: keypadInput.keypadInput,
	[74]: laundryDryerControls.laundryDryerControls,
	[83]: laundryWasherControls.laundryWasherControls,
	[8]: levelControl.levelControl,
	[43]: localizationConfiguration.localizationConfiguration,
	[44]: localizationTimeFormat.timeFormatLocalization,
	[45]: localizationUnit.unitLocalization,
	[1288]: lowPower.lowPower,
	[1287]: mediaInput.mediaInput,
	[1286]: mediaPlayback.mediaPlayback,
	[151]: messages.messages,
	[2822]: meterIdentification.meterIdentification,
	[95]: microwaveOvenControl.microwaveOvenControl,
	[80]: modeSelect.modeSelect,
	[159]: modeDeviceEnergyManagement.deviceEnergyManagementMode,
	[89]: modeDishwasher.dishwasherMode,
	[157]: modeEVSE.energyEVSEMode,
	[81]: modeLaundryWasher.laundryWasherMode,
	[94]: modeMicrowaveOven.microwaveOvenMode,
	[73]: modeOven.ovenMode,
	[85]: modeRVCClean.rVCCleanMode,
	[84]: modeRVCRun.rVCRunMode,
	[82]: modeRefrigerator.refrigeratorAndTemperatureControlledCabinetMode,
	[158]: modeWaterHeater.waterHeaterMode,
	[49]: networkCommissioningCluster.networkCommissioning,
	[41]: oTAProvider.oTASoftwareUpdateProvider,
	[42]: oTARequestor.oTASoftwareUpdateRequestor,
	[1030]: occupancySensing.occupancySensing,
	[6]: onOff.onOff,
	[62]: operationalCredentialCluster.operationalCredentials,
	[96]: operationalState.operationalState,
	[72]: operationalStateOven.ovenCavityOperationalState,
	[97]: operationalStateRVC.rVCOperationalState,
	[47]: powerSourceCluster.powerSource,
	[46]: powerSourceConfigurationCluster.powerSourceConfiguration,
	[156]: powerTopology.powerTopology,
	[1027]: pressureMeasurement.pressureMeasurement,
	[512]: pumpConfigurationControl.pumpConfigurationAndControl,
	[1365]: pushAVStreamTransport.pushAVStreamTransport,
	[87]: refrigeratorAlarm.refrigeratorAlarm,
	[113]: resourceMonitoring.hEPAFilterMonitoring,
	[114]: resourceMonitoring.activatedCarbonFilterMonitoring,
	[121]: resourceMonitoring.waterTankLevelMonitoring,
	[98]: scenes.scenesManagement,
	[336]: serviceArea.serviceArea,
	[92]: smokeCOAlarm.smokeCOAlarm,
	[1072]: soilMeasurement.soilMeasurement,
	[59]: switch_.switch_,
	[2049]: tLSCertificateManagement.tLSCertificateManagement,
	[2050]: tLSClientManagement.tLSClientManagement,
	[1285]: targetNavigator.targetNavigator,
	[86]: temperatureControl.temperatureControl,
	[1026]: temperatureMeasurement.temperatureMeasurement,
	[513]: thermostat.thermostat,
	[516]: thermostatUserInterfaceConfiguration.thermostatUserInterfaceConfiguration,
	[1106]: threadBorderRouterManagement.threadBorderRouterManagement,
	[1107]: threadNetworkDirectory.threadNetworkDirectory,
	[56]: timeSync.timeSynchronization,
	[65]: userLabelCluster.userLabel,
	[129]: valveConfigurationControl.valveConfigurationAndControl,
	[1283]: wakeOnLAN.wakeOnLAN,
	[1029]: waterContentMeasurement.relativeHumidityMeasurement,
	[148]: waterHeaterManagement.waterHeaterManagement,
	[1363]: webRTCProvider.webRTCTransportProvider,
	[1364]: webRTCRequestor.webRTCTransportRequestor,
	[1105]: wiFiNetworkManagement.wiFiNetworkManagement,
	[258]: windowCovering.windowCovering,
	[1360]: zoneManagement.zoneManagement,
}

export enum ClusterIdNames {
	accessControl = ClusterIds.AccessControl,
	accountLogin = ClusterIds.AccountLogin,
	actions = ClusterIds.Actions,
	administratorCommissioning = ClusterIds.AdministratorCommissioning,
	airQuality = ClusterIds.AirQuality,
	applicationBasic = ClusterIds.ApplicationBasic,
	applicationLauncher = ClusterIds.ApplicationLauncher,
	audioOutput = ClusterIds.AudioOutput,
	basicInformation = ClusterIds.BasicInformation,
	binding = ClusterIds.Binding,
	booleanState = ClusterIds.BooleanState,
	booleanStateConfiguration = ClusterIds.BooleanStateConfiguration,
	bridgedDeviceBasicInformation = ClusterIds.BridgedDeviceBasicInformation,
	cameraAVSettingsUserLevelManagement = ClusterIds.CameraAVSettingsUserLevelManagement,
	cameraAVStreamManagement = ClusterIds.CameraAVStreamManagement,
	channel = ClusterIds.Channel,
	chime = ClusterIds.Chime,
	closureControl = ClusterIds.ClosureControl,
	closureDimension = ClusterIds.ClosureDimension,
	colorControl = ClusterIds.ColorControl,
	commissionerControl = ClusterIds.CommissionerControl,
	commodityMetering = ClusterIds.CommodityMetering,
	commodityPrice = ClusterIds.CommodityPrice,
	commodityTariff = ClusterIds.CommodityTariff,
	carbonMonoxideConcentrationMeasurement = ClusterIds.CarbonMonoxideConcentrationMeasurement,
	carbonDioxideConcentrationMeasurement = ClusterIds.CarbonDioxideConcentrationMeasurement,
	nitrogenDioxideConcentrationMeasurement = ClusterIds.NitrogenDioxideConcentrationMeasurement,
	ozoneConcentrationMeasurement = ClusterIds.OzoneConcentrationMeasurement,
	pM2_5ConcentrationMeasurement = ClusterIds.PM2_5ConcentrationMeasurement,
	formaldehydeConcentrationMeasurement = ClusterIds.FormaldehydeConcentrationMeasurement,
	pM1ConcentrationMeasurement = ClusterIds.PM1ConcentrationMeasurement,
	pM10ConcentrationMeasurement = ClusterIds.PM10ConcentrationMeasurement,
	totalVolatileOrganicCompoundsConcentrationMeasurement = ClusterIds.TotalVolatileOrganicCompoundsConcentrationMeasurement,
	radonConcentrationMeasurement = ClusterIds.RadonConcentrationMeasurement,
	contentAppObserver = ClusterIds.ContentAppObserver,
	contentControl = ClusterIds.ContentControl,
	contentLauncher = ClusterIds.ContentLauncher,
	descriptor = ClusterIds.Descriptor,
	deviceEnergyManagement = ClusterIds.DeviceEnergyManagement,
	diagnosticLogs = ClusterIds.DiagnosticLogs,
	ethernetNetworkDiagnostics = ClusterIds.EthernetNetworkDiagnostics,
	generalDiagnostics = ClusterIds.GeneralDiagnostics,
	softwareDiagnostics = ClusterIds.SoftwareDiagnostics,
	threadNetworkDiagnostics = ClusterIds.ThreadNetworkDiagnostics,
	wiFiNetworkDiagnostics = ClusterIds.WiFiNetworkDiagnostics,
	dishwasherAlarm = ClusterIds.DishwasherAlarm,
	doorLock = ClusterIds.DoorLock,
	ecosystemInformation = ClusterIds.EcosystemInformation,
	electricalEnergyMeasurement = ClusterIds.ElectricalEnergyMeasurement,
	electricalGridConditions = ClusterIds.ElectricalGridConditions,
	electricalPowerMeasurement = ClusterIds.ElectricalPowerMeasurement,
	energyEVSE = ClusterIds.EnergyEVSE,
	energyPreference = ClusterIds.EnergyPreference,
	fanControl = ClusterIds.FanControl,
	fixedLabel = ClusterIds.FixedLabel,
	flowMeasurement = ClusterIds.FlowMeasurement,
	generalCommissioning = ClusterIds.GeneralCommissioning,
	groupKeyManagement = ClusterIds.GroupKeyManagement,
	groups = ClusterIds.Groups,
	iCDManagement = ClusterIds.ICDManagement,
	identify = ClusterIds.Identify,
	illuminanceMeasurement = ClusterIds.IlluminanceMeasurement,
	jointFabricAdministrator = ClusterIds.JointFabricAdministrator,
	jointFabricDatastore = ClusterIds.JointFabricDatastore,
	keypadInput = ClusterIds.KeypadInput,
	laundryDryerControls = ClusterIds.LaundryDryerControls,
	laundryWasherControls = ClusterIds.LaundryWasherControls,
	levelControl = ClusterIds.LevelControl,
	localizationConfiguration = ClusterIds.LocalizationConfiguration,
	timeFormatLocalization = ClusterIds.TimeFormatLocalization,
	unitLocalization = ClusterIds.UnitLocalization,
	lowPower = ClusterIds.LowPower,
	mediaInput = ClusterIds.MediaInput,
	mediaPlayback = ClusterIds.MediaPlayback,
	messages = ClusterIds.Messages,
	meterIdentification = ClusterIds.MeterIdentification,
	microwaveOvenControl = ClusterIds.MicrowaveOvenControl,
	modeSelect = ClusterIds.ModeSelect,
	deviceEnergyManagementMode = ClusterIds.DeviceEnergyManagementMode,
	dishwasherMode = ClusterIds.DishwasherMode,
	energyEVSEMode = ClusterIds.EnergyEVSEMode,
	laundryWasherMode = ClusterIds.LaundryWasherMode,
	microwaveOvenMode = ClusterIds.MicrowaveOvenMode,
	ovenMode = ClusterIds.OvenMode,
	rVCCleanMode = ClusterIds.RVCCleanMode,
	rVCRunMode = ClusterIds.RVCRunMode,
	refrigeratorAndTemperatureControlledCabinetMode = ClusterIds.RefrigeratorAndTemperatureControlledCabinetMode,
	waterHeaterMode = ClusterIds.WaterHeaterMode,
	networkCommissioning = ClusterIds.NetworkCommissioning,
	oTASoftwareUpdateProvider = ClusterIds.OTASoftwareUpdateProvider,
	oTASoftwareUpdateRequestor = ClusterIds.OTASoftwareUpdateRequestor,
	occupancySensing = ClusterIds.OccupancySensing,
	onOff = ClusterIds.OnOff,
	operationalCredentials = ClusterIds.OperationalCredentials,
	operationalState = ClusterIds.OperationalState,
	ovenCavityOperationalState = ClusterIds.OvenCavityOperationalState,
	rVCOperationalState = ClusterIds.RVCOperationalState,
	powerSource = ClusterIds.PowerSource,
	powerSourceConfiguration = ClusterIds.PowerSourceConfiguration,
	powerTopology = ClusterIds.PowerTopology,
	pressureMeasurement = ClusterIds.PressureMeasurement,
	pumpConfigurationAndControl = ClusterIds.PumpConfigurationAndControl,
	pushAVStreamTransport = ClusterIds.PushAVStreamTransport,
	refrigeratorAlarm = ClusterIds.RefrigeratorAlarm,
	hEPAFilterMonitoring = ClusterIds.HEPAFilterMonitoring,
	activatedCarbonFilterMonitoring = ClusterIds.ActivatedCarbonFilterMonitoring,
	waterTankLevelMonitoring = ClusterIds.WaterTankLevelMonitoring,
	scenesManagement = ClusterIds.ScenesManagement,
	serviceArea = ClusterIds.ServiceArea,
	smokeCOAlarm = ClusterIds.SmokeCOAlarm,
	soilMeasurement = ClusterIds.SoilMeasurement,
	switch_ = ClusterIds.Switch,
	tLSCertificateManagement = ClusterIds.TLSCertificateManagement,
	tLSClientManagement = ClusterIds.TLSClientManagement,
	targetNavigator = ClusterIds.TargetNavigator,
	temperatureControl = ClusterIds.TemperatureControl,
	temperatureMeasurement = ClusterIds.TemperatureMeasurement,
	thermostat = ClusterIds.Thermostat,
	thermostatUserInterfaceConfiguration = ClusterIds.ThermostatUserInterfaceConfiguration,
	threadBorderRouterManagement = ClusterIds.ThreadBorderRouterManagement,
	threadNetworkDirectory = ClusterIds.ThreadNetworkDirectory,
	timeSynchronization = ClusterIds.TimeSynchronization,
	userLabel = ClusterIds.UserLabel,
	valveConfigurationAndControl = ClusterIds.ValveConfigurationAndControl,
	wakeOnLAN = ClusterIds.WakeOnLAN,
	relativeHumidityMeasurement = ClusterIds.RelativeHumidityMeasurement,
	waterHeaterManagement = ClusterIds.WaterHeaterManagement,
	webRTCTransportProvider = ClusterIds.WebRTCTransportProvider,
	webRTCTransportRequestor = ClusterIds.WebRTCTransportRequestor,
	wiFiNetworkManagement = ClusterIds.WiFiNetworkManagement,
	windowCovering = ClusterIds.WindowCovering,
	zoneManagement = ClusterIds.ZoneManagement,
}

export type ReverseClusterIdNames = {
	[31]: 'accessControl',
	[1294]: 'accountLogin',
	[37]: 'actions',
	[60]: 'administratorCommissioning',
	[91]: 'airQuality',
	[1293]: 'applicationBasic',
	[1292]: 'applicationLauncher',
	[1291]: 'audioOutput',
	[40]: 'basicInformation',
	[30]: 'binding',
	[69]: 'booleanState',
	[128]: 'booleanStateConfiguration',
	[57]: 'bridgedDeviceBasicInformation',
	[1362]: 'cameraAVSettingsUserLevelManagement',
	[1361]: 'cameraAVStreamManagement',
	[1284]: 'channel',
	[1366]: 'chime',
	[260]: 'closureControl',
	[261]: 'closureDimension',
	[768]: 'colorControl',
	[1873]: 'commissionerControl',
	[2823]: 'commodityMetering',
	[149]: 'commodityPrice',
	[1792]: 'commodityTariff',
	[1036]: 'carbonMonoxideConcentrationMeasurement',
	[1037]: 'carbonDioxideConcentrationMeasurement',
	[1043]: 'nitrogenDioxideConcentrationMeasurement',
	[1045]: 'ozoneConcentrationMeasurement',
	[1066]: 'pM2_5ConcentrationMeasurement',
	[1067]: 'formaldehydeConcentrationMeasurement',
	[1068]: 'pM1ConcentrationMeasurement',
	[1069]: 'pM10ConcentrationMeasurement',
	[1070]: 'totalVolatileOrganicCompoundsConcentrationMeasurement',
	[1071]: 'radonConcentrationMeasurement',
	[1296]: 'contentAppObserver',
	[1295]: 'contentControl',
	[1290]: 'contentLauncher',
	[29]: 'descriptor',
	[152]: 'deviceEnergyManagement',
	[50]: 'diagnosticLogs',
	[55]: 'ethernetNetworkDiagnostics',
	[51]: 'generalDiagnostics',
	[52]: 'softwareDiagnostics',
	[53]: 'threadNetworkDiagnostics',
	[54]: 'wiFiNetworkDiagnostics',
	[93]: 'dishwasherAlarm',
	[257]: 'doorLock',
	[1872]: 'ecosystemInformation',
	[145]: 'electricalEnergyMeasurement',
	[160]: 'electricalGridConditions',
	[144]: 'electricalPowerMeasurement',
	[153]: 'energyEVSE',
	[155]: 'energyPreference',
	[514]: 'fanControl',
	[64]: 'fixedLabel',
	[1028]: 'flowMeasurement',
	[48]: 'generalCommissioning',
	[63]: 'groupKeyManagement',
	[4]: 'groups',
	[70]: 'iCDManagement',
	[3]: 'identify',
	[1024]: 'illuminanceMeasurement',
	[1875]: 'jointFabricAdministrator',
	[1874]: 'jointFabricDatastore',
	[1289]: 'keypadInput',
	[74]: 'laundryDryerControls',
	[83]: 'laundryWasherControls',
	[8]: 'levelControl',
	[43]: 'localizationConfiguration',
	[44]: 'timeFormatLocalization',
	[45]: 'unitLocalization',
	[1288]: 'lowPower',
	[1287]: 'mediaInput',
	[1286]: 'mediaPlayback',
	[151]: 'messages',
	[2822]: 'meterIdentification',
	[95]: 'microwaveOvenControl',
	[80]: 'modeSelect',
	[159]: 'deviceEnergyManagementMode',
	[89]: 'dishwasherMode',
	[157]: 'energyEVSEMode',
	[81]: 'laundryWasherMode',
	[94]: 'microwaveOvenMode',
	[73]: 'ovenMode',
	[85]: 'rVCCleanMode',
	[84]: 'rVCRunMode',
	[82]: 'refrigeratorAndTemperatureControlledCabinetMode',
	[158]: 'waterHeaterMode',
	[49]: 'networkCommissioning',
	[41]: 'oTASoftwareUpdateProvider',
	[42]: 'oTASoftwareUpdateRequestor',
	[1030]: 'occupancySensing',
	[6]: 'onOff',
	[62]: 'operationalCredentials',
	[96]: 'operationalState',
	[72]: 'ovenCavityOperationalState',
	[97]: 'rVCOperationalState',
	[47]: 'powerSource',
	[46]: 'powerSourceConfiguration',
	[156]: 'powerTopology',
	[1027]: 'pressureMeasurement',
	[512]: 'pumpConfigurationAndControl',
	[1365]: 'pushAVStreamTransport',
	[87]: 'refrigeratorAlarm',
	[113]: 'hEPAFilterMonitoring',
	[114]: 'activatedCarbonFilterMonitoring',
	[121]: 'waterTankLevelMonitoring',
	[98]: 'scenesManagement',
	[336]: 'serviceArea',
	[92]: 'smokeCOAlarm',
	[1072]: 'soilMeasurement',
	[59]: 'switch_',
	[2049]: 'tLSCertificateManagement',
	[2050]: 'tLSClientManagement',
	[1285]: 'targetNavigator',
	[86]: 'temperatureControl',
	[1026]: 'temperatureMeasurement',
	[513]: 'thermostat',
	[516]: 'thermostatUserInterfaceConfiguration',
	[1106]: 'threadBorderRouterManagement',
	[1107]: 'threadNetworkDirectory',
	[56]: 'timeSynchronization',
	[65]: 'userLabel',
	[129]: 'valveConfigurationAndControl',
	[1283]: 'wakeOnLAN',
	[1029]: 'relativeHumidityMeasurement',
	[148]: 'waterHeaterManagement',
	[1363]: 'webRTCTransportProvider',
	[1364]: 'webRTCTransportRequestor',
	[1105]: 'wiFiNetworkManagement',
	[258]: 'windowCovering',
	[1360]: 'zoneManagement',
}