import * as accessControlCluster from "./access-control-cluster.js";
export { accessControlCluster }; import * as accessControlDefinitions from "./access-control-definitions.js";
export { accessControlDefinitions }; import * as accountLoginCluster from "./account-login-cluster.js";
export { accountLoginCluster }; import * as actionsCluster from "./actions-cluster.js";
export { actionsCluster }; import * as administratorCommissioningCluster from "./administrator-commissioning-cluster.js";
export { administratorCommissioningCluster }; import * as airQualityCluster from "./air-quality-cluster.js";
export { airQualityCluster }; import * as applicationBasicCluster from "./application-basic-cluster.js";
export { applicationBasicCluster }; import * as applicationLauncherCluster from "./application-launcher-cluster.js";
export { applicationLauncherCluster }; import * as audioOutputCluster from "./audio-output-cluster.js";
export { audioOutputCluster }; import * as ballastConfigurationCluster from "./ballast-configuration-cluster.js";
export { ballastConfigurationCluster }; import * as basicInformationCluster from "./basic-information-cluster.js";
export { basicInformationCluster }; import * as bindingCluster from "./binding-cluster.js";
export { bindingCluster }; import * as booleanStateCluster from "./boolean-state-cluster.js";
export { booleanStateCluster }; import * as booleanStateConfigurationCluster from "./boolean-state-configuration-cluster.js";
export { booleanStateConfigurationCluster }; import * as bridgedDeviceBasicInformationCluster from "./bridged-device-basic-information-cluster.js";
export { bridgedDeviceBasicInformationCluster }; import * as cameraAvSettingsUserLevelManagementCluster from "./camera-av-settings-user-level-management-cluster.js";
export { cameraAvSettingsUserLevelManagementCluster }; import * as cameraAvStreamManagementCluster from "./camera-av-stream-management-cluster.js";
export { cameraAvStreamManagementCluster }; import * as channelCluster from "./channel-cluster.js";
export { channelCluster }; import * as chimeCluster from "./chime-cluster.js";
export { chimeCluster }; import * as chipOta from "./chip-ota.js";
export { chipOta }; import * as chipTypes from "./chip-types.js";
export { chipTypes }; import * as closureControlCluster from "./closure-control-cluster.js";
export { closureControlCluster }; import * as closureDimensionCluster from "./closure-dimension-cluster.js";
export { closureDimensionCluster }; import * as clustersExtensions from "./clusters-extensions.js";
export { clustersExtensions }; import * as colorControlCluster from "./color-control-cluster.js";
export { colorControlCluster }; import * as commissionerControlCluster from "./commissioner-control-cluster.js";
export { commissionerControlCluster }; import * as commodityMeteringCluster from "./commodity-metering-cluster.js";
export { commodityMeteringCluster }; import * as commodityPriceCluster from "./commodity-price-cluster.js";
export { commodityPriceCluster }; import * as commodityTariffCluster from "./commodity-tariff-cluster.js";
export { commodityTariffCluster }; import * as concentrationMeasurementCluster from "./concentration-measurement-cluster.js";
export { concentrationMeasurementCluster }; import * as contentAppObserverCluster from "./content-app-observer-cluster.js";
export { contentAppObserverCluster }; import * as contentControlCluster from "./content-control-cluster.js";
export { contentControlCluster }; import * as contentLaunchCluster from "./content-launch-cluster.js";
export { contentLaunchCluster }; import * as descriptorCluster from "./descriptor-cluster.js";
export { descriptorCluster }; import * as deviceEnergyManagementCluster from "./device-energy-management-cluster.js";
export { deviceEnergyManagementCluster }; import * as deviceEnergyManagementModeCluster from "./device-energy-management-mode-cluster.js";
export { deviceEnergyManagementModeCluster }; import * as diagnosticLogsCluster from "./diagnostic-logs-cluster.js";
export { diagnosticLogsCluster }; import * as dishwasherAlarmCluster from "./dishwasher-alarm-cluster.js";
export { dishwasherAlarmCluster }; import * as dishwasherModeCluster from "./dishwasher-mode-cluster.js";
export { dishwasherModeCluster }; import * as doorLockCluster from "./door-lock-cluster.js";
export { doorLockCluster }; import * as ecosystemInformationCluster from "./ecosystem-information-cluster.js";
export { ecosystemInformationCluster }; import * as electricalEnergyMeasurementCluster from "./electrical-energy-measurement-cluster.js";
export { electricalEnergyMeasurementCluster }; import * as electricalGridConditionsCluster from "./electrical-grid-conditions-cluster.js";
export { electricalGridConditionsCluster }; import * as electricalPowerMeasurementCluster from "./electrical-power-measurement-cluster.js";
export { electricalPowerMeasurementCluster }; import * as energyEvseCluster from "./energy-evse-cluster.js";
export { energyEvseCluster }; import * as energyEvseModeCluster from "./energy-evse-mode-cluster.js";
export { energyEvseModeCluster }; import * as energyPreferenceCluster from "./energy-preference-cluster.js";
export { energyPreferenceCluster }; import * as ethernetNetworkDiagnosticsCluster from "./ethernet-network-diagnostics-cluster.js";
export { ethernetNetworkDiagnosticsCluster }; import * as fanControlCluster from "./fan-control-cluster.js";
export { fanControlCluster }; import * as faultInjectionCluster from "./fault-injection-cluster.js";
export { faultInjectionCluster }; import * as fixedLabelCluster from "./fixed-label-cluster.js";
export { fixedLabelCluster }; import * as flowMeasurementCluster from "./flow-measurement-cluster.js";
export { flowMeasurementCluster }; import * as generalCommissioningCluster from "./general-commissioning-cluster.js";
export { generalCommissioningCluster }; import * as generalDiagnosticsCluster from "./general-diagnostics-cluster.js";
export { generalDiagnosticsCluster }; import * as globalAttributes from "./global-attributes.js";
export { globalAttributes }; import * as globalBitmaps from "./global-bitmaps.js";
export { globalBitmaps }; import * as globalEnums from "./global-enums.js";
export { globalEnums }; import * as globalStructs from "./global-structs.js";
export { globalStructs }; import * as groupKeyMgmtCluster from "./group-key-mgmt-cluster.js";
export { groupKeyMgmtCluster }; import * as groupsCluster from "./groups-cluster.js";
export { groupsCluster }; import * as icdManagementCluster from "./icd-management-cluster.js";
export { icdManagementCluster }; import * as identifyCluster from "./identify-cluster.js";
export { identifyCluster }; import * as illuminanceMeasurementCluster from "./illuminance-measurement-cluster.js";
export { illuminanceMeasurementCluster }; import * as jointFabricAdministratorCluster from "./joint-fabric-administrator-cluster.js";
export { jointFabricAdministratorCluster }; import * as jointFabricDatastoreCluster from "./joint-fabric-datastore-cluster.js";
export { jointFabricDatastoreCluster }; import * as keypadInputCluster from "./keypad-input-cluster.js";
export { keypadInputCluster }; import * as laundryDryerControlsCluster from "./laundry-dryer-controls-cluster.js";
export { laundryDryerControlsCluster }; import * as laundryWasherModeCluster from "./laundry-washer-mode-cluster.js";
export { laundryWasherModeCluster }; import * as levelControlCluster from "./level-control-cluster.js";
export { levelControlCluster }; import * as localizationConfigurationCluster from "./localization-configuration-cluster.js";
export { localizationConfigurationCluster }; import * as lowPowerCluster from "./low-power-cluster.js";
export { lowPowerCluster }; import * as matterDevices from "./matter-devices.js";
export { matterDevices }; import * as measurementAndSensing from "./measurement-and-sensing.js";
export { measurementAndSensing }; import * as mediaInputCluster from "./media-input-cluster.js";
export { mediaInputCluster }; import * as mediaPlaybackCluster from "./media-playback-cluster.js";
export { mediaPlaybackCluster }; import * as messagesCluster from "./messages-cluster.js";
export { messagesCluster }; import * as meterIdentificationCluster from "./meter-identification-cluster.js";
export { meterIdentificationCluster }; import * as microwaveOvenControlCluster from "./microwave-oven-control-cluster.js";
export { microwaveOvenControlCluster }; import * as microwaveOvenModeCluster from "./microwave-oven-mode-cluster.js";
export { microwaveOvenModeCluster }; import * as modeBaseCluster from "./mode-base-cluster.js";
export { modeBaseCluster }; import * as modeSelectCluster from "./mode-select-cluster.js";
export { modeSelectCluster }; import * as networkCommissioningCluster from "./network-commissioning-cluster.js";
export { networkCommissioningCluster }; import * as occupancySensingCluster from "./occupancy-sensing-cluster.js";
export { occupancySensingCluster }; import * as onoffCluster from "./onoff-cluster.js";
export { onoffCluster }; import * as operationalCredentialsCluster from "./operational-credentials-cluster.js";
export { operationalCredentialsCluster }; import * as operationalStateCluster from "./operational-state-cluster.js";
export { operationalStateCluster }; import * as operationalStateOvenCluster from "./operational-state-oven-cluster.js";
export { operationalStateOvenCluster }; import * as operationalStateRvcCluster from "./operational-state-rvc-cluster.js";
export { operationalStateRvcCluster }; import * as ovenModeCluster from "./oven-mode-cluster.js";
export { ovenModeCluster }; import * as powerSourceCluster from "./power-source-cluster.js";
export { powerSourceCluster }; import * as powerSourceConfigurationCluster from "./power-source-configuration-cluster.js";
export { powerSourceConfigurationCluster }; import * as powerTopologyCluster from "./power-topology-cluster.js";
export { powerTopologyCluster }; import * as pressureMeasurementCluster from "./pressure-measurement-cluster.js";
export { pressureMeasurementCluster }; import * as proxyConfigurationCluster from "./proxy-configuration-cluster.js";
export { proxyConfigurationCluster }; import * as proxyDiscoveryCluster from "./proxy-discovery-cluster.js";
export { proxyDiscoveryCluster }; import * as proxyValidCluster from "./proxy-valid-cluster.js";
export { proxyValidCluster }; import * as pumpConfigurationAndControlCluster from "./pump-configuration-and-control-cluster.js";
export { pumpConfigurationAndControlCluster }; import * as pushAvStreamTransportCluster from "./push-av-stream-transport-cluster.js";
export { pushAvStreamTransportCluster }; import * as pwmCluster from "./pwm-cluster.js";
export { pwmCluster }; import * as refrigeratorAlarm from "./refrigerator-alarm.js";
export { refrigeratorAlarm }; import * as refrigeratorAndTemperatureControlledCabinetModeCluster from "./refrigerator-and-temperature-controlled-cabinet-mode-cluster.js";
export { refrigeratorAndTemperatureControlledCabinetModeCluster }; import * as relativeHumidityMeasurementCluster from "./relative-humidity-measurement-cluster.js";
export { relativeHumidityMeasurementCluster }; import * as resourceMonitoringCluster from "./resource-monitoring-cluster.js";
export { resourceMonitoringCluster }; import * as rvcCleanModeCluster from "./rvc-clean-mode-cluster.js";
export { rvcCleanModeCluster }; import * as rvcRunModeCluster from "./rvc-run-mode-cluster.js";
export { rvcRunModeCluster }; import * as sampleMeiCluster from "./sample-mei-cluster.js";
export { sampleMeiCluster }; import * as scene from "./scene.js";
export { scene }; import * as semanticTagNamespaceEnums from "./semantic-tag-namespace-enums.js";
export { semanticTagNamespaceEnums }; import * as serviceAreaCluster from "./service-area-cluster.js";
export { serviceAreaCluster }; import * as smokeCoAlarmCluster from "./smoke-co-alarm-cluster.js";
export { smokeCoAlarmCluster }; import * as softwareDiagnosticsCluster from "./software-diagnostics-cluster.js";
export { softwareDiagnosticsCluster }; import * as soilMeasurementCluster from "./soil-measurement-cluster.js";
export { soilMeasurementCluster }; import * as switchCluster from "./switch-cluster.js";
export { switchCluster }; import * as targetNavigatorCluster from "./target-navigator-cluster.js";
export { targetNavigatorCluster }; import * as temperatureControlCluster from "./temperature-control-cluster.js";
export { temperatureControlCluster }; import * as temperatureMeasurementCluster from "./temperature-measurement-cluster.js";
export { temperatureMeasurementCluster }; import * as testCluster from "./test-cluster.js";
export { testCluster }; import * as thermostatCluster from "./thermostat-cluster.js";
export { thermostatCluster }; import * as thermostatUserInterfaceConfigurationCluster from "./thermostat-user-interface-configuration-cluster.js";
export { thermostatUserInterfaceConfigurationCluster }; import * as threadBorderRouterManagementCluster from "./thread-border-router-management-cluster.js";
export { threadBorderRouterManagementCluster }; import * as threadNetworkDiagnosticsCluster from "./thread-network-diagnostics-cluster.js";
export { threadNetworkDiagnosticsCluster }; import * as threadNetworkDirectoryCluster from "./thread-network-directory-cluster.js";
export { threadNetworkDirectoryCluster }; import * as timeFormatLocalizationCluster from "./time-format-localization-cluster.js";
export { timeFormatLocalizationCluster }; import * as timeSynchronizationCluster from "./time-synchronization-cluster.js";
export { timeSynchronizationCluster }; import * as timerCluster from "./timer-cluster.js";
export { timerCluster }; import * as tlsCertificateManagementCluster from "./tls-certificate-management-cluster.js";
export { tlsCertificateManagementCluster }; import * as tlsClientManagementCluster from "./tls-client-management-cluster.js";
export { tlsClientManagementCluster }; import * as unitLocalizationCluster from "./unit-localization-cluster.js";
export { unitLocalizationCluster }; import * as userLabelCluster from "./user-label-cluster.js";
export { userLabelCluster }; import * as valveConfigurationAndControlCluster from "./valve-configuration-and-control-cluster.js";
export { valveConfigurationAndControlCluster }; import * as wakeOnLanCluster from "./wake-on-lan-cluster.js";
export { wakeOnLanCluster }; import * as washerControlsCluster from "./washer-controls-cluster.js";
export { washerControlsCluster }; import * as waterHeaterManagementCluster from "./water-heater-management-cluster.js";
export { waterHeaterManagementCluster }; import * as waterHeaterModeCluster from "./water-heater-mode-cluster.js";
export { waterHeaterModeCluster }; import * as webrtcProviderCluster from "./webrtc-provider-cluster.js";
export { webrtcProviderCluster }; import * as webrtcRequestorCluster from "./webrtc-requestor-cluster.js";
export { webrtcRequestorCluster }; import * as wifiNetworkDiagnosticsCluster from "./wifi-network-diagnostics-cluster.js";
export { wifiNetworkDiagnosticsCluster }; import * as wifiNetworkManagementCluster from "./wifi-network-management-cluster.js";
export { wifiNetworkManagementCluster }; import * as windowCovering from "./window-covering.js";
export { windowCovering }; import * as zoneManagementCluster from "./zone-management-cluster.js";
export { zoneManagementCluster };

export enum ClusterIds
{
	AccessControl = 31,
	AccountLogin = 1294,
	Actions = 37,
	AdministratorCommissioning = 60,
	AirQuality = 91,
	ApplicationBasic = 1293,
	ApplicationLauncher = 1292,
	AudioOutput = 1291,
	BallastConfiguration = 769,
	BasicInformation = 40,
	Binding = 30,
	BooleanState = 69,
	BooleanStateConfiguration = 128,
	BridgedDeviceBasicInformation = 57,
	CameraAVSettingsUserLevelManagement = 1362,
	CameraAVStreamManagement = 1361,
	Channel = 1284,
	Chime = 1366,
	OTASoftwareUpdateProvider = 41,
	OTASoftwareUpdateRequestor = 42,
	ClosureControl = 260,
	ClosureDimension = 261,
	ColorControl = 768,
	CommissionerControl = 1873,
	CommodityMetering = 2823,
	CommodityPrice = 149,
	CommodityTariff = 1792,
	CarbonMonoxideConcentrationMeasurement = 1036,
	CarbonDioxideConcentrationMeasurement = 1037,
	NitrogenDioxideConcentrationMeasurement = 1043,
	OzoneConcentrationMeasurement = 1045,
	PM2_5ConcentrationMeasurement = 1066,
	FormaldehydeConcentrationMeasurement = 1067,
	PM1ConcentrationMeasurement = 1068,
	PM10ConcentrationMeasurement = 1069,
	TotalVolatileOrganicCompoundsConcentrationMeasurement = 1070,
	RadonConcentrationMeasurement = 1071,
	ContentAppObserver = 1296,
	ContentControl = 1295,
	ContentLauncher = 1290,
	Descriptor = 29,
	DeviceEnergyManagement = 152,
	DeviceEnergyManagementMode = 159,
	DiagnosticLogs = 50,
	DishwasherAlarm = 93,
	DishwasherMode = 89,
	DoorLock = 257,
	EcosystemInformation = 1872,
	ElectricalEnergyMeasurement = 145,
	ElectricalGridConditions = 160,
	ElectricalPowerMeasurement = 144,
	EnergyEVSE = 153,
	EnergyEVSEMode = 157,
	EnergyPreference = 155,
	EthernetNetworkDiagnostics = 55,
	FanControl = 514,
	FaultInjection = 4294048774,
	FixedLabel = 64,
	FlowMeasurement = 1028,
	GeneralCommissioning = 48,
	GeneralDiagnostics = 51,
	GroupKeyManagement = 63,
	Groups = 4,
	ICDManagement = 70,
	Identify = 3,
	IlluminanceMeasurement = 1024,
	JointFabricAdministrator = 1875,
	JointFabricDatastore = 1874,
	KeypadInput = 1289,
	LaundryDryerControls = 74,
	LaundryWasherMode = 81,
	LevelControl = 8,
	LocalizationConfiguration = 43,
	LowPower = 1288,
	MediaInput = 1287,
	MediaPlayback = 1286,
	Messages = 151,
	MeterIdentification = 2822,
	MicrowaveOvenControl = 95,
	MicrowaveOvenMode = 94,
	ModeSelect = 80,
	NetworkCommissioning = 49,
	OccupancySensing = 1030,
	OnOff = 6,
	OperationalCredentials = 62,
	OperationalState = 96,
	OvenCavityOperationalState = 72,
	RVCOperationalState = 97,
	OvenMode = 73,
	PowerSource = 47,
	PowerSourceConfiguration = 46,
	PowerTopology = 156,
	PressureMeasurement = 1027,
	ProxyConfiguration = 66,
	ProxyDiscovery = 67,
	ProxyValid = 68,
	PumpConfigurationAndControl = 512,
	PushAVStreamTransport = 1365,
	PulseWidthModulation = 28,
	RefrigeratorAlarm = 87,
	RefrigeratorAndTemperatureControlledCabinetMode = 82,
	RelativeHumidityMeasurement = 1029,
	HEPAFilterMonitoring = 113,
	ActivatedCarbonFilterMonitoring = 114,
	RVCCleanMode = 85,
	RVCRunMode = 84,
	SampleMEI = 4294048800,
	ScenesManagement = 98,
	ServiceArea = 336,
	SmokeCOAlarm = 92,
	SoftwareDiagnostics = 52,
	SoilMeasurement = 1072,
	Switch = 59,
	TargetNavigator = 1285,
	TemperatureControl = 86,
	TemperatureMeasurement = 1026,
	UnitTesting = 4294048773,
	Thermostat = 513,
	ThermostatUserInterfaceConfiguration = 516,
	ThreadBorderRouterManagement = 1106,
	ThreadNetworkDiagnostics = 53,
	ThreadNetworkDirectory = 1107,
	TimeFormatLocalization = 44,
	TimeSynchronization = 56,
	Timer = 71,
	TLSCertificateManagement = 2049,
	TLSClientManagement = 2050,
	UnitLocalization = 45,
	UserLabel = 65,
	ValveConfigurationAndControl = 129,
	WakeOnLAN = 1283,
	LaundryWasherControls = 83,
	WaterHeaterManagement = 148,
	WaterHeaterMode = 158,
	WebRTCTransportProvider = 1363,
	WebRTCTransportRequestor = 1364,
	WiFiNetworkDiagnostics = 54,
	WiFiNetworkManagement = 1105,
	WindowCovering = 258,
	ZoneManagement = 1360,
}

export type ClusterIdMap = {
	[ClusterIds.AccessControl]: accessControlCluster.AccessControl,
	[ClusterIds.AccountLogin]: accountLoginCluster.AccountLogin,
	[ClusterIds.Actions]: actionsCluster.Actions,
	[ClusterIds.AdministratorCommissioning]: administratorCommissioningCluster.AdministratorCommissioning,
	[ClusterIds.AirQuality]: airQualityCluster.AirQuality,
	[ClusterIds.ApplicationBasic]: applicationBasicCluster.ApplicationBasic,
	[ClusterIds.ApplicationLauncher]: applicationLauncherCluster.ApplicationLauncher,
	[ClusterIds.AudioOutput]: audioOutputCluster.AudioOutput,
	[ClusterIds.BallastConfiguration]: ballastConfigurationCluster.BallastConfiguration,
	[ClusterIds.BasicInformation]: basicInformationCluster.BasicInformation,
	[ClusterIds.Binding]: bindingCluster.Binding,
	[ClusterIds.BooleanState]: booleanStateCluster.BooleanState,
	[ClusterIds.BooleanStateConfiguration]: booleanStateConfigurationCluster.BooleanStateConfiguration,
	[ClusterIds.BridgedDeviceBasicInformation]: bridgedDeviceBasicInformationCluster.BridgedDeviceBasicInformation,
	[ClusterIds.CameraAVSettingsUserLevelManagement]: cameraAvSettingsUserLevelManagementCluster.CameraAVSettingsUserLevelManagement,
	[ClusterIds.CameraAVStreamManagement]: cameraAvStreamManagementCluster.CameraAVStreamManagement,
	[ClusterIds.Channel]: channelCluster.Channel,
	[ClusterIds.Chime]: chimeCluster.Chime,
	[ClusterIds.OTASoftwareUpdateProvider]: chipOta.OTASoftwareUpdateProvider,
	[ClusterIds.OTASoftwareUpdateRequestor]: chipOta.OTASoftwareUpdateRequestor,
	[ClusterIds.ClosureControl]: closureControlCluster.ClosureControl,
	[ClusterIds.ClosureDimension]: closureDimensionCluster.ClosureDimension,
	[ClusterIds.ColorControl]: colorControlCluster.ColorControl,
	[ClusterIds.CommissionerControl]: commissionerControlCluster.CommissionerControl,
	[ClusterIds.CommodityMetering]: commodityMeteringCluster.CommodityMetering,
	[ClusterIds.CommodityPrice]: commodityPriceCluster.CommodityPrice,
	[ClusterIds.CommodityTariff]: commodityTariffCluster.CommodityTariff,
	[ClusterIds.CarbonMonoxideConcentrationMeasurement]: concentrationMeasurementCluster.CarbonMonoxideConcentrationMeasurement,
	[ClusterIds.CarbonDioxideConcentrationMeasurement]: concentrationMeasurementCluster.CarbonDioxideConcentrationMeasurement,
	[ClusterIds.NitrogenDioxideConcentrationMeasurement]: concentrationMeasurementCluster.NitrogenDioxideConcentrationMeasurement,
	[ClusterIds.OzoneConcentrationMeasurement]: concentrationMeasurementCluster.OzoneConcentrationMeasurement,
	[ClusterIds.PM2_5ConcentrationMeasurement]: concentrationMeasurementCluster.PM2_5ConcentrationMeasurement,
	[ClusterIds.FormaldehydeConcentrationMeasurement]: concentrationMeasurementCluster.FormaldehydeConcentrationMeasurement,
	[ClusterIds.PM1ConcentrationMeasurement]: concentrationMeasurementCluster.PM1ConcentrationMeasurement,
	[ClusterIds.PM10ConcentrationMeasurement]: concentrationMeasurementCluster.PM10ConcentrationMeasurement,
	[ClusterIds.TotalVolatileOrganicCompoundsConcentrationMeasurement]: concentrationMeasurementCluster.TotalVolatileOrganicCompoundsConcentrationMeasurement,
	[ClusterIds.RadonConcentrationMeasurement]: concentrationMeasurementCluster.RadonConcentrationMeasurement,
	[ClusterIds.ContentAppObserver]: contentAppObserverCluster.ContentAppObserver,
	[ClusterIds.ContentControl]: contentControlCluster.ContentControl,
	[ClusterIds.ContentLauncher]: contentLaunchCluster.ContentLauncher,
	[ClusterIds.Descriptor]: descriptorCluster.Descriptor,
	[ClusterIds.DeviceEnergyManagement]: deviceEnergyManagementCluster.DeviceEnergyManagement,
	[ClusterIds.DeviceEnergyManagementMode]: deviceEnergyManagementModeCluster.DeviceEnergyManagementMode,
	[ClusterIds.DiagnosticLogs]: diagnosticLogsCluster.DiagnosticLogs,
	[ClusterIds.DishwasherAlarm]: dishwasherAlarmCluster.DishwasherAlarm,
	[ClusterIds.DishwasherMode]: dishwasherModeCluster.DishwasherMode,
	[ClusterIds.DoorLock]: doorLockCluster.DoorLock,
	[ClusterIds.EcosystemInformation]: ecosystemInformationCluster.EcosystemInformation,
	[ClusterIds.ElectricalEnergyMeasurement]: electricalEnergyMeasurementCluster.ElectricalEnergyMeasurement,
	[ClusterIds.ElectricalGridConditions]: electricalGridConditionsCluster.ElectricalGridConditions,
	[ClusterIds.ElectricalPowerMeasurement]: electricalPowerMeasurementCluster.ElectricalPowerMeasurement,
	[ClusterIds.EnergyEVSE]: energyEvseCluster.EnergyEVSE,
	[ClusterIds.EnergyEVSEMode]: energyEvseModeCluster.EnergyEVSEMode,
	[ClusterIds.EnergyPreference]: energyPreferenceCluster.EnergyPreference,
	[ClusterIds.EthernetNetworkDiagnostics]: ethernetNetworkDiagnosticsCluster.EthernetNetworkDiagnostics,
	[ClusterIds.FanControl]: fanControlCluster.FanControl,
	[ClusterIds.FaultInjection]: faultInjectionCluster.FaultInjection,
	[ClusterIds.FixedLabel]: fixedLabelCluster.FixedLabel,
	[ClusterIds.FlowMeasurement]: flowMeasurementCluster.FlowMeasurement,
	[ClusterIds.GeneralCommissioning]: generalCommissioningCluster.GeneralCommissioning,
	[ClusterIds.GeneralDiagnostics]: generalDiagnosticsCluster.GeneralDiagnostics,
	[ClusterIds.GroupKeyManagement]: groupKeyMgmtCluster.GroupKeyManagement,
	[ClusterIds.Groups]: groupsCluster.Groups,
	[ClusterIds.ICDManagement]: icdManagementCluster.ICDManagement,
	[ClusterIds.Identify]: identifyCluster.Identify,
	[ClusterIds.IlluminanceMeasurement]: illuminanceMeasurementCluster.IlluminanceMeasurement,
	[ClusterIds.JointFabricAdministrator]: jointFabricAdministratorCluster.JointFabricAdministrator,
	[ClusterIds.JointFabricDatastore]: jointFabricDatastoreCluster.JointFabricDatastore,
	[ClusterIds.KeypadInput]: keypadInputCluster.KeypadInput,
	[ClusterIds.LaundryDryerControls]: laundryDryerControlsCluster.LaundryDryerControls,
	[ClusterIds.LaundryWasherMode]: laundryWasherModeCluster.LaundryWasherMode,
	[ClusterIds.LevelControl]: levelControlCluster.LevelControl,
	[ClusterIds.LocalizationConfiguration]: localizationConfigurationCluster.LocalizationConfiguration,
	[ClusterIds.LowPower]: lowPowerCluster.LowPower,
	[ClusterIds.MediaInput]: mediaInputCluster.MediaInput,
	[ClusterIds.MediaPlayback]: mediaPlaybackCluster.MediaPlayback,
	[ClusterIds.Messages]: messagesCluster.Messages,
	[ClusterIds.MeterIdentification]: meterIdentificationCluster.MeterIdentification,
	[ClusterIds.MicrowaveOvenControl]: microwaveOvenControlCluster.MicrowaveOvenControl,
	[ClusterIds.MicrowaveOvenMode]: microwaveOvenModeCluster.MicrowaveOvenMode,
	[ClusterIds.ModeSelect]: modeSelectCluster.ModeSelect,
	[ClusterIds.NetworkCommissioning]: networkCommissioningCluster.NetworkCommissioning,
	[ClusterIds.OccupancySensing]: occupancySensingCluster.OccupancySensing,
	[ClusterIds.OnOff]: onoffCluster.OnOff,
	[ClusterIds.OperationalCredentials]: operationalCredentialsCluster.OperationalCredentials,
	[ClusterIds.OperationalState]: operationalStateCluster.OperationalState,
	[ClusterIds.OvenCavityOperationalState]: operationalStateOvenCluster.OvenCavityOperationalState,
	[ClusterIds.RVCOperationalState]: operationalStateRvcCluster.RVCOperationalState,
	[ClusterIds.OvenMode]: ovenModeCluster.OvenMode,
	[ClusterIds.PowerSource]: powerSourceCluster.PowerSource,
	[ClusterIds.PowerSourceConfiguration]: powerSourceConfigurationCluster.PowerSourceConfiguration,
	[ClusterIds.PowerTopology]: powerTopologyCluster.PowerTopology,
	[ClusterIds.PressureMeasurement]: pressureMeasurementCluster.PressureMeasurement,
	[ClusterIds.ProxyConfiguration]: proxyConfigurationCluster.ProxyConfiguration,
	[ClusterIds.ProxyDiscovery]: proxyDiscoveryCluster.ProxyDiscovery,
	[ClusterIds.ProxyValid]: proxyValidCluster.ProxyValid,
	[ClusterIds.PumpConfigurationAndControl]: pumpConfigurationAndControlCluster.PumpConfigurationAndControl,
	[ClusterIds.PushAVStreamTransport]: pushAvStreamTransportCluster.PushAVStreamTransport,
	[ClusterIds.PulseWidthModulation]: pwmCluster.PulseWidthModulation,
	[ClusterIds.RefrigeratorAlarm]: refrigeratorAlarm.RefrigeratorAlarm,
	[ClusterIds.RefrigeratorAndTemperatureControlledCabinetMode]: refrigeratorAndTemperatureControlledCabinetModeCluster.RefrigeratorAndTemperatureControlledCabinetMode,
	[ClusterIds.RelativeHumidityMeasurement]: relativeHumidityMeasurementCluster.RelativeHumidityMeasurement,
	[ClusterIds.HEPAFilterMonitoring]: resourceMonitoringCluster.HEPAFilterMonitoring,
	[ClusterIds.ActivatedCarbonFilterMonitoring]: resourceMonitoringCluster.ActivatedCarbonFilterMonitoring,
	[ClusterIds.RVCCleanMode]: rvcCleanModeCluster.RVCCleanMode,
	[ClusterIds.RVCRunMode]: rvcRunModeCluster.RVCRunMode,
	[ClusterIds.SampleMEI]: sampleMeiCluster.SampleMEI,
	[ClusterIds.ScenesManagement]: scene.ScenesManagement,
	[ClusterIds.ServiceArea]: serviceAreaCluster.ServiceArea,
	[ClusterIds.SmokeCOAlarm]: smokeCoAlarmCluster.SmokeCOAlarm,
	[ClusterIds.SoftwareDiagnostics]: softwareDiagnosticsCluster.SoftwareDiagnostics,
	[ClusterIds.SoilMeasurement]: soilMeasurementCluster.SoilMeasurement,
	[ClusterIds.Switch]: switchCluster.Switch,
	[ClusterIds.TargetNavigator]: targetNavigatorCluster.TargetNavigator,
	[ClusterIds.TemperatureControl]: temperatureControlCluster.TemperatureControl,
	[ClusterIds.TemperatureMeasurement]: temperatureMeasurementCluster.TemperatureMeasurement,
	[ClusterIds.UnitTesting]: testCluster.UnitTesting,
	[ClusterIds.Thermostat]: thermostatCluster.Thermostat,
	[ClusterIds.ThermostatUserInterfaceConfiguration]: thermostatUserInterfaceConfigurationCluster.ThermostatUserInterfaceConfiguration,
	[ClusterIds.ThreadBorderRouterManagement]: threadBorderRouterManagementCluster.ThreadBorderRouterManagement,
	[ClusterIds.ThreadNetworkDiagnostics]: threadNetworkDiagnosticsCluster.ThreadNetworkDiagnostics,
	[ClusterIds.ThreadNetworkDirectory]: threadNetworkDirectoryCluster.ThreadNetworkDirectory,
	[ClusterIds.TimeFormatLocalization]: timeFormatLocalizationCluster.TimeFormatLocalization,
	[ClusterIds.TimeSynchronization]: timeSynchronizationCluster.TimeSynchronization,
	[ClusterIds.Timer]: timerCluster.Timer,
	[ClusterIds.TLSCertificateManagement]: tlsCertificateManagementCluster.TLSCertificateManagement,
	[ClusterIds.TLSClientManagement]: tlsClientManagementCluster.TLSClientManagement,
	[ClusterIds.UnitLocalization]: unitLocalizationCluster.UnitLocalization,
	[ClusterIds.UserLabel]: userLabelCluster.UserLabel,
	[ClusterIds.ValveConfigurationAndControl]: valveConfigurationAndControlCluster.ValveConfigurationAndControl,
	[ClusterIds.WakeOnLAN]: wakeOnLanCluster.WakeOnLAN,
	[ClusterIds.LaundryWasherControls]: washerControlsCluster.LaundryWasherControls,
	[ClusterIds.WaterHeaterManagement]: waterHeaterManagementCluster.WaterHeaterManagement,
	[ClusterIds.WaterHeaterMode]: waterHeaterModeCluster.WaterHeaterMode,
	[ClusterIds.WebRTCTransportProvider]: webrtcProviderCluster.WebRTCTransportProvider,
	[ClusterIds.WebRTCTransportRequestor]: webrtcRequestorCluster.WebRTCTransportRequestor,
	[ClusterIds.WiFiNetworkDiagnostics]: wifiNetworkDiagnosticsCluster.WiFiNetworkDiagnostics,
	[ClusterIds.WiFiNetworkManagement]: wifiNetworkManagementCluster.WiFiNetworkManagement,
	[ClusterIds.WindowCovering]: windowCovering.WindowCovering,
	[ClusterIds.ZoneManagement]: zoneManagementCluster.ZoneManagement,
}

export type ClusterMap = {
	accessControl: accessControlCluster.AccessControl,
	accountLogin: accountLoginCluster.AccountLogin,
	actions: actionsCluster.Actions,
	administratorCommissioning: administratorCommissioningCluster.AdministratorCommissioning,
	airQuality: airQualityCluster.AirQuality,
	applicationBasic: applicationBasicCluster.ApplicationBasic,
	applicationLauncher: applicationLauncherCluster.ApplicationLauncher,
	audioOutput: audioOutputCluster.AudioOutput,
	ballastConfiguration: ballastConfigurationCluster.BallastConfiguration,
	basicInformation: basicInformationCluster.BasicInformation,
	binding: bindingCluster.Binding,
	booleanState: booleanStateCluster.BooleanState,
	booleanStateConfiguration: booleanStateConfigurationCluster.BooleanStateConfiguration,
	bridgedDeviceBasicInformation: bridgedDeviceBasicInformationCluster.BridgedDeviceBasicInformation,
	cameraAVSettingsUserLevelManagement: cameraAvSettingsUserLevelManagementCluster.CameraAVSettingsUserLevelManagement,
	cameraAVStreamManagement: cameraAvStreamManagementCluster.CameraAVStreamManagement,
	channel: channelCluster.Channel,
	chime: chimeCluster.Chime,
	oTASoftwareUpdateProvider: chipOta.OTASoftwareUpdateProvider,
	oTASoftwareUpdateRequestor: chipOta.OTASoftwareUpdateRequestor,
	closureControl: closureControlCluster.ClosureControl,
	closureDimension: closureDimensionCluster.ClosureDimension,
	colorControl: colorControlCluster.ColorControl,
	commissionerControl: commissionerControlCluster.CommissionerControl,
	commodityMetering: commodityMeteringCluster.CommodityMetering,
	commodityPrice: commodityPriceCluster.CommodityPrice,
	commodityTariff: commodityTariffCluster.CommodityTariff,
	carbonMonoxideConcentrationMeasurement: concentrationMeasurementCluster.CarbonMonoxideConcentrationMeasurement,
	carbonDioxideConcentrationMeasurement: concentrationMeasurementCluster.CarbonDioxideConcentrationMeasurement,
	nitrogenDioxideConcentrationMeasurement: concentrationMeasurementCluster.NitrogenDioxideConcentrationMeasurement,
	ozoneConcentrationMeasurement: concentrationMeasurementCluster.OzoneConcentrationMeasurement,
	pM2_5ConcentrationMeasurement: concentrationMeasurementCluster.PM2_5ConcentrationMeasurement,
	formaldehydeConcentrationMeasurement: concentrationMeasurementCluster.FormaldehydeConcentrationMeasurement,
	pM1ConcentrationMeasurement: concentrationMeasurementCluster.PM1ConcentrationMeasurement,
	pM10ConcentrationMeasurement: concentrationMeasurementCluster.PM10ConcentrationMeasurement,
	totalVolatileOrganicCompoundsConcentrationMeasurement: concentrationMeasurementCluster.TotalVolatileOrganicCompoundsConcentrationMeasurement,
	radonConcentrationMeasurement: concentrationMeasurementCluster.RadonConcentrationMeasurement,
	contentAppObserver: contentAppObserverCluster.ContentAppObserver,
	contentControl: contentControlCluster.ContentControl,
	contentLauncher: contentLaunchCluster.ContentLauncher,
	descriptor: descriptorCluster.Descriptor,
	deviceEnergyManagement: deviceEnergyManagementCluster.DeviceEnergyManagement,
	deviceEnergyManagementMode: deviceEnergyManagementModeCluster.DeviceEnergyManagementMode,
	diagnosticLogs: diagnosticLogsCluster.DiagnosticLogs,
	dishwasherAlarm: dishwasherAlarmCluster.DishwasherAlarm,
	dishwasherMode: dishwasherModeCluster.DishwasherMode,
	doorLock: doorLockCluster.DoorLock,
	ecosystemInformation: ecosystemInformationCluster.EcosystemInformation,
	electricalEnergyMeasurement: electricalEnergyMeasurementCluster.ElectricalEnergyMeasurement,
	electricalGridConditions: electricalGridConditionsCluster.ElectricalGridConditions,
	electricalPowerMeasurement: electricalPowerMeasurementCluster.ElectricalPowerMeasurement,
	energyEVSE: energyEvseCluster.EnergyEVSE,
	energyEVSEMode: energyEvseModeCluster.EnergyEVSEMode,
	energyPreference: energyPreferenceCluster.EnergyPreference,
	ethernetNetworkDiagnostics: ethernetNetworkDiagnosticsCluster.EthernetNetworkDiagnostics,
	fanControl: fanControlCluster.FanControl,
	faultInjection: faultInjectionCluster.FaultInjection,
	fixedLabel: fixedLabelCluster.FixedLabel,
	flowMeasurement: flowMeasurementCluster.FlowMeasurement,
	generalCommissioning: generalCommissioningCluster.GeneralCommissioning,
	generalDiagnostics: generalDiagnosticsCluster.GeneralDiagnostics,
	groupKeyManagement: groupKeyMgmtCluster.GroupKeyManagement,
	groups: groupsCluster.Groups,
	iCDManagement: icdManagementCluster.ICDManagement,
	identify: identifyCluster.Identify,
	illuminanceMeasurement: illuminanceMeasurementCluster.IlluminanceMeasurement,
	jointFabricAdministrator: jointFabricAdministratorCluster.JointFabricAdministrator,
	jointFabricDatastore: jointFabricDatastoreCluster.JointFabricDatastore,
	keypadInput: keypadInputCluster.KeypadInput,
	laundryDryerControls: laundryDryerControlsCluster.LaundryDryerControls,
	laundryWasherMode: laundryWasherModeCluster.LaundryWasherMode,
	levelControl: levelControlCluster.LevelControl,
	localizationConfiguration: localizationConfigurationCluster.LocalizationConfiguration,
	lowPower: lowPowerCluster.LowPower,
	mediaInput: mediaInputCluster.MediaInput,
	mediaPlayback: mediaPlaybackCluster.MediaPlayback,
	messages: messagesCluster.Messages,
	meterIdentification: meterIdentificationCluster.MeterIdentification,
	microwaveOvenControl: microwaveOvenControlCluster.MicrowaveOvenControl,
	microwaveOvenMode: microwaveOvenModeCluster.MicrowaveOvenMode,
	modeSelect: modeSelectCluster.ModeSelect,
	networkCommissioning: networkCommissioningCluster.NetworkCommissioning,
	occupancySensing: occupancySensingCluster.OccupancySensing,
	onOff: onoffCluster.OnOff,
	operationalCredentials: operationalCredentialsCluster.OperationalCredentials,
	operationalState: operationalStateCluster.OperationalState,
	ovenCavityOperationalState: operationalStateOvenCluster.OvenCavityOperationalState,
	rVCOperationalState: operationalStateRvcCluster.RVCOperationalState,
	ovenMode: ovenModeCluster.OvenMode,
	powerSource: powerSourceCluster.PowerSource,
	powerSourceConfiguration: powerSourceConfigurationCluster.PowerSourceConfiguration,
	powerTopology: powerTopologyCluster.PowerTopology,
	pressureMeasurement: pressureMeasurementCluster.PressureMeasurement,
	proxyConfiguration: proxyConfigurationCluster.ProxyConfiguration,
	proxyDiscovery: proxyDiscoveryCluster.ProxyDiscovery,
	proxyValid: proxyValidCluster.ProxyValid,
	pumpConfigurationAndControl: pumpConfigurationAndControlCluster.PumpConfigurationAndControl,
	pushAVStreamTransport: pushAvStreamTransportCluster.PushAVStreamTransport,
	pulseWidthModulation: pwmCluster.PulseWidthModulation,
	refrigeratorAlarm: refrigeratorAlarm.RefrigeratorAlarm,
	refrigeratorAndTemperatureControlledCabinetMode: refrigeratorAndTemperatureControlledCabinetModeCluster.RefrigeratorAndTemperatureControlledCabinetMode,
	relativeHumidityMeasurement: relativeHumidityMeasurementCluster.RelativeHumidityMeasurement,
	hEPAFilterMonitoring: resourceMonitoringCluster.HEPAFilterMonitoring,
	activatedCarbonFilterMonitoring: resourceMonitoringCluster.ActivatedCarbonFilterMonitoring,
	rVCCleanMode: rvcCleanModeCluster.RVCCleanMode,
	rVCRunMode: rvcRunModeCluster.RVCRunMode,
	sampleMEI: sampleMeiCluster.SampleMEI,
	scenesManagement: scene.ScenesManagement,
	serviceArea: serviceAreaCluster.ServiceArea,
	smokeCOAlarm: smokeCoAlarmCluster.SmokeCOAlarm,
	softwareDiagnostics: softwareDiagnosticsCluster.SoftwareDiagnostics,
	soilMeasurement: soilMeasurementCluster.SoilMeasurement,
	switch: switchCluster.Switch,
	targetNavigator: targetNavigatorCluster.TargetNavigator,
	temperatureControl: temperatureControlCluster.TemperatureControl,
	temperatureMeasurement: temperatureMeasurementCluster.TemperatureMeasurement,
	unitTesting: testCluster.UnitTesting,
	thermostat: thermostatCluster.Thermostat,
	thermostatUserInterfaceConfiguration: thermostatUserInterfaceConfigurationCluster.ThermostatUserInterfaceConfiguration,
	threadBorderRouterManagement: threadBorderRouterManagementCluster.ThreadBorderRouterManagement,
	threadNetworkDiagnostics: threadNetworkDiagnosticsCluster.ThreadNetworkDiagnostics,
	threadNetworkDirectory: threadNetworkDirectoryCluster.ThreadNetworkDirectory,
	timeFormatLocalization: timeFormatLocalizationCluster.TimeFormatLocalization,
	timeSynchronization: timeSynchronizationCluster.TimeSynchronization,
	timer: timerCluster.Timer,
	tLSCertificateManagement: tlsCertificateManagementCluster.TLSCertificateManagement,
	tLSClientManagement: tlsClientManagementCluster.TLSClientManagement,
	unitLocalization: unitLocalizationCluster.UnitLocalization,
	userLabel: userLabelCluster.UserLabel,
	valveConfigurationAndControl: valveConfigurationAndControlCluster.ValveConfigurationAndControl,
	wakeOnLAN: wakeOnLanCluster.WakeOnLAN,
	laundryWasherControls: washerControlsCluster.LaundryWasherControls,
	waterHeaterManagement: waterHeaterManagementCluster.WaterHeaterManagement,
	waterHeaterMode: waterHeaterModeCluster.WaterHeaterMode,
	webRTCTransportProvider: webrtcProviderCluster.WebRTCTransportProvider,
	webRTCTransportRequestor: webrtcRequestorCluster.WebRTCTransportRequestor,
	wiFiNetworkDiagnostics: wifiNetworkDiagnosticsCluster.WiFiNetworkDiagnostics,
	wiFiNetworkManagement: wifiNetworkManagementCluster.WiFiNetworkManagement,
	windowCovering: windowCovering.WindowCovering,
	zoneManagement: zoneManagementCluster.ZoneManagement,
}

export enum ClusterIdNames
{
	accessControl = ClusterIds.AccessControl,
	accountLogin = ClusterIds.AccountLogin,
	actions = ClusterIds.Actions,
	administratorCommissioning = ClusterIds.AdministratorCommissioning,
	airQuality = ClusterIds.AirQuality,
	applicationBasic = ClusterIds.ApplicationBasic,
	applicationLauncher = ClusterIds.ApplicationLauncher,
	audioOutput = ClusterIds.AudioOutput,
	ballastConfiguration = ClusterIds.BallastConfiguration,
	basicInformation = ClusterIds.BasicInformation,
	binding = ClusterIds.Binding,
	booleanState = ClusterIds.BooleanState,
	booleanStateConfiguration = ClusterIds.BooleanStateConfiguration,
	bridgedDeviceBasicInformation = ClusterIds.BridgedDeviceBasicInformation,
	cameraAVSettingsUserLevelManagement = ClusterIds.CameraAVSettingsUserLevelManagement,
	cameraAVStreamManagement = ClusterIds.CameraAVStreamManagement,
	channel = ClusterIds.Channel,
	chime = ClusterIds.Chime,
	oTASoftwareUpdateProvider = ClusterIds.OTASoftwareUpdateProvider,
	oTASoftwareUpdateRequestor = ClusterIds.OTASoftwareUpdateRequestor,
	closureControl = ClusterIds.ClosureControl,
	closureDimension = ClusterIds.ClosureDimension,
	colorControl = ClusterIds.ColorControl,
	commissionerControl = ClusterIds.CommissionerControl,
	commodityMetering = ClusterIds.CommodityMetering,
	commodityPrice = ClusterIds.CommodityPrice,
	commodityTariff = ClusterIds.CommodityTariff,
	carbonMonoxideConcentrationMeasurement = ClusterIds.CarbonMonoxideConcentrationMeasurement,
	carbonDioxideConcentrationMeasurement = ClusterIds.CarbonDioxideConcentrationMeasurement,
	nitrogenDioxideConcentrationMeasurement = ClusterIds.NitrogenDioxideConcentrationMeasurement,
	ozoneConcentrationMeasurement = ClusterIds.OzoneConcentrationMeasurement,
	pM2_5ConcentrationMeasurement = ClusterIds.PM2_5ConcentrationMeasurement,
	formaldehydeConcentrationMeasurement = ClusterIds.FormaldehydeConcentrationMeasurement,
	pM1ConcentrationMeasurement = ClusterIds.PM1ConcentrationMeasurement,
	pM10ConcentrationMeasurement = ClusterIds.PM10ConcentrationMeasurement,
	totalVolatileOrganicCompoundsConcentrationMeasurement = ClusterIds.TotalVolatileOrganicCompoundsConcentrationMeasurement,
	radonConcentrationMeasurement = ClusterIds.RadonConcentrationMeasurement,
	contentAppObserver = ClusterIds.ContentAppObserver,
	contentControl = ClusterIds.ContentControl,
	contentLauncher = ClusterIds.ContentLauncher,
	descriptor = ClusterIds.Descriptor,
	deviceEnergyManagement = ClusterIds.DeviceEnergyManagement,
	deviceEnergyManagementMode = ClusterIds.DeviceEnergyManagementMode,
	diagnosticLogs = ClusterIds.DiagnosticLogs,
	dishwasherAlarm = ClusterIds.DishwasherAlarm,
	dishwasherMode = ClusterIds.DishwasherMode,
	doorLock = ClusterIds.DoorLock,
	ecosystemInformation = ClusterIds.EcosystemInformation,
	electricalEnergyMeasurement = ClusterIds.ElectricalEnergyMeasurement,
	electricalGridConditions = ClusterIds.ElectricalGridConditions,
	electricalPowerMeasurement = ClusterIds.ElectricalPowerMeasurement,
	energyEVSE = ClusterIds.EnergyEVSE,
	energyEVSEMode = ClusterIds.EnergyEVSEMode,
	energyPreference = ClusterIds.EnergyPreference,
	ethernetNetworkDiagnostics = ClusterIds.EthernetNetworkDiagnostics,
	fanControl = ClusterIds.FanControl,
	faultInjection = ClusterIds.FaultInjection,
	fixedLabel = ClusterIds.FixedLabel,
	flowMeasurement = ClusterIds.FlowMeasurement,
	generalCommissioning = ClusterIds.GeneralCommissioning,
	generalDiagnostics = ClusterIds.GeneralDiagnostics,
	groupKeyManagement = ClusterIds.GroupKeyManagement,
	groups = ClusterIds.Groups,
	iCDManagement = ClusterIds.ICDManagement,
	identify = ClusterIds.Identify,
	illuminanceMeasurement = ClusterIds.IlluminanceMeasurement,
	jointFabricAdministrator = ClusterIds.JointFabricAdministrator,
	jointFabricDatastore = ClusterIds.JointFabricDatastore,
	keypadInput = ClusterIds.KeypadInput,
	laundryDryerControls = ClusterIds.LaundryDryerControls,
	laundryWasherMode = ClusterIds.LaundryWasherMode,
	levelControl = ClusterIds.LevelControl,
	localizationConfiguration = ClusterIds.LocalizationConfiguration,
	lowPower = ClusterIds.LowPower,
	mediaInput = ClusterIds.MediaInput,
	mediaPlayback = ClusterIds.MediaPlayback,
	messages = ClusterIds.Messages,
	meterIdentification = ClusterIds.MeterIdentification,
	microwaveOvenControl = ClusterIds.MicrowaveOvenControl,
	microwaveOvenMode = ClusterIds.MicrowaveOvenMode,
	modeSelect = ClusterIds.ModeSelect,
	networkCommissioning = ClusterIds.NetworkCommissioning,
	occupancySensing = ClusterIds.OccupancySensing,
	onOff = ClusterIds.OnOff,
	operationalCredentials = ClusterIds.OperationalCredentials,
	operationalState = ClusterIds.OperationalState,
	ovenCavityOperationalState = ClusterIds.OvenCavityOperationalState,
	rVCOperationalState = ClusterIds.RVCOperationalState,
	ovenMode = ClusterIds.OvenMode,
	powerSource = ClusterIds.PowerSource,
	powerSourceConfiguration = ClusterIds.PowerSourceConfiguration,
	powerTopology = ClusterIds.PowerTopology,
	pressureMeasurement = ClusterIds.PressureMeasurement,
	proxyConfiguration = ClusterIds.ProxyConfiguration,
	proxyDiscovery = ClusterIds.ProxyDiscovery,
	proxyValid = ClusterIds.ProxyValid,
	pumpConfigurationAndControl = ClusterIds.PumpConfigurationAndControl,
	pushAVStreamTransport = ClusterIds.PushAVStreamTransport,
	pulseWidthModulation = ClusterIds.PulseWidthModulation,
	refrigeratorAlarm = ClusterIds.RefrigeratorAlarm,
	refrigeratorAndTemperatureControlledCabinetMode = ClusterIds.RefrigeratorAndTemperatureControlledCabinetMode,
	relativeHumidityMeasurement = ClusterIds.RelativeHumidityMeasurement,
	hEPAFilterMonitoring = ClusterIds.HEPAFilterMonitoring,
	activatedCarbonFilterMonitoring = ClusterIds.ActivatedCarbonFilterMonitoring,
	rVCCleanMode = ClusterIds.RVCCleanMode,
	rVCRunMode = ClusterIds.RVCRunMode,
	sampleMEI = ClusterIds.SampleMEI,
	scenesManagement = ClusterIds.ScenesManagement,
	serviceArea = ClusterIds.ServiceArea,
	smokeCOAlarm = ClusterIds.SmokeCOAlarm,
	softwareDiagnostics = ClusterIds.SoftwareDiagnostics,
	soilMeasurement = ClusterIds.SoilMeasurement,
	switch = ClusterIds.Switch,
	targetNavigator = ClusterIds.TargetNavigator,
	temperatureControl = ClusterIds.TemperatureControl,
	temperatureMeasurement = ClusterIds.TemperatureMeasurement,
	unitTesting = ClusterIds.UnitTesting,
	thermostat = ClusterIds.Thermostat,
	thermostatUserInterfaceConfiguration = ClusterIds.ThermostatUserInterfaceConfiguration,
	threadBorderRouterManagement = ClusterIds.ThreadBorderRouterManagement,
	threadNetworkDiagnostics = ClusterIds.ThreadNetworkDiagnostics,
	threadNetworkDirectory = ClusterIds.ThreadNetworkDirectory,
	timeFormatLocalization = ClusterIds.TimeFormatLocalization,
	timeSynchronization = ClusterIds.TimeSynchronization,
	timer = ClusterIds.Timer,
	tLSCertificateManagement = ClusterIds.TLSCertificateManagement,
	tLSClientManagement = ClusterIds.TLSClientManagement,
	unitLocalization = ClusterIds.UnitLocalization,
	userLabel = ClusterIds.UserLabel,
	valveConfigurationAndControl = ClusterIds.ValveConfigurationAndControl,
	wakeOnLAN = ClusterIds.WakeOnLAN,
	laundryWasherControls = ClusterIds.LaundryWasherControls,
	waterHeaterManagement = ClusterIds.WaterHeaterManagement,
	waterHeaterMode = ClusterIds.WaterHeaterMode,
	webRTCTransportProvider = ClusterIds.WebRTCTransportProvider,
	webRTCTransportRequestor = ClusterIds.WebRTCTransportRequestor,
	wiFiNetworkDiagnostics = ClusterIds.WiFiNetworkDiagnostics,
	wiFiNetworkManagement = ClusterIds.WiFiNetworkManagement,
	windowCovering = ClusterIds.WindowCovering,
	zoneManagement = ClusterIds.ZoneManagement,
}

export type ReverseClusterIdNames = {
	[31]: 'accessControl',
	[1294]: 'accountLogin',
	[37]: 'actions',
	[60]: 'administratorCommissioning',
	[91]: 'airQuality',
	[1293]: 'applicationBasic',
	[1292]: 'applicationLauncher',
	[1291]: 'audioOutput',
	[769]: 'ballastConfiguration',
	[40]: 'basicInformation',
	[30]: 'binding',
	[69]: 'booleanState',
	[128]: 'booleanStateConfiguration',
	[57]: 'bridgedDeviceBasicInformation',
	[1362]: 'cameraAVSettingsUserLevelManagement',
	[1361]: 'cameraAVStreamManagement',
	[1284]: 'channel',
	[1366]: 'chime',
	[41]: 'oTASoftwareUpdateProvider',
	[42]: 'oTASoftwareUpdateRequestor',
	[260]: 'closureControl',
	[261]: 'closureDimension',
	[768]: 'colorControl',
	[1873]: 'commissionerControl',
	[2823]: 'commodityMetering',
	[149]: 'commodityPrice',
	[1792]: 'commodityTariff',
	[1036]: 'carbonMonoxideConcentrationMeasurement',
	[1037]: 'carbonDioxideConcentrationMeasurement',
	[1043]: 'nitrogenDioxideConcentrationMeasurement',
	[1045]: 'ozoneConcentrationMeasurement',
	[1066]: 'pM2_5ConcentrationMeasurement',
	[1067]: 'formaldehydeConcentrationMeasurement',
	[1068]: 'pM1ConcentrationMeasurement',
	[1069]: 'pM10ConcentrationMeasurement',
	[1070]: 'totalVolatileOrganicCompoundsConcentrationMeasurement',
	[1071]: 'radonConcentrationMeasurement',
	[1296]: 'contentAppObserver',
	[1295]: 'contentControl',
	[1290]: 'contentLauncher',
	[29]: 'descriptor',
	[152]: 'deviceEnergyManagement',
	[159]: 'deviceEnergyManagementMode',
	[50]: 'diagnosticLogs',
	[93]: 'dishwasherAlarm',
	[89]: 'dishwasherMode',
	[257]: 'doorLock',
	[1872]: 'ecosystemInformation',
	[145]: 'electricalEnergyMeasurement',
	[160]: 'electricalGridConditions',
	[144]: 'electricalPowerMeasurement',
	[153]: 'energyEVSE',
	[157]: 'energyEVSEMode',
	[155]: 'energyPreference',
	[55]: 'ethernetNetworkDiagnostics',
	[514]: 'fanControl',
	[4294048774]: 'faultInjection',
	[64]: 'fixedLabel',
	[1028]: 'flowMeasurement',
	[48]: 'generalCommissioning',
	[51]: 'generalDiagnostics',
	[63]: 'groupKeyManagement',
	[4]: 'groups',
	[70]: 'iCDManagement',
	[3]: 'identify',
	[1024]: 'illuminanceMeasurement',
	[1875]: 'jointFabricAdministrator',
	[1874]: 'jointFabricDatastore',
	[1289]: 'keypadInput',
	[74]: 'laundryDryerControls',
	[81]: 'laundryWasherMode',
	[8]: 'levelControl',
	[43]: 'localizationConfiguration',
	[1288]: 'lowPower',
	[1287]: 'mediaInput',
	[1286]: 'mediaPlayback',
	[151]: 'messages',
	[2822]: 'meterIdentification',
	[95]: 'microwaveOvenControl',
	[94]: 'microwaveOvenMode',
	[80]: 'modeSelect',
	[49]: 'networkCommissioning',
	[1030]: 'occupancySensing',
	[6]: 'onOff',
	[62]: 'operationalCredentials',
	[96]: 'operationalState',
	[72]: 'ovenCavityOperationalState',
	[97]: 'rVCOperationalState',
	[73]: 'ovenMode',
	[47]: 'powerSource',
	[46]: 'powerSourceConfiguration',
	[156]: 'powerTopology',
	[1027]: 'pressureMeasurement',
	[66]: 'proxyConfiguration',
	[67]: 'proxyDiscovery',
	[68]: 'proxyValid',
	[512]: 'pumpConfigurationAndControl',
	[1365]: 'pushAVStreamTransport',
	[28]: 'pulseWidthModulation',
	[87]: 'refrigeratorAlarm',
	[82]: 'refrigeratorAndTemperatureControlledCabinetMode',
	[1029]: 'relativeHumidityMeasurement',
	[113]: 'hEPAFilterMonitoring',
	[114]: 'activatedCarbonFilterMonitoring',
	[85]: 'rVCCleanMode',
	[84]: 'rVCRunMode',
	[4294048800]: 'sampleMEI',
	[98]: 'scenesManagement',
	[336]: 'serviceArea',
	[92]: 'smokeCOAlarm',
	[52]: 'softwareDiagnostics',
	[1072]: 'soilMeasurement',
	[59]: 'switch',
	[1285]: 'targetNavigator',
	[86]: 'temperatureControl',
	[1026]: 'temperatureMeasurement',
	[4294048773]: 'unitTesting',
	[513]: 'thermostat',
	[516]: 'thermostatUserInterfaceConfiguration',
	[1106]: 'threadBorderRouterManagement',
	[53]: 'threadNetworkDiagnostics',
	[1107]: 'threadNetworkDirectory',
	[44]: 'timeFormatLocalization',
	[56]: 'timeSynchronization',
	[71]: 'timer',
	[2049]: 'tLSCertificateManagement',
	[2050]: 'tLSClientManagement',
	[45]: 'unitLocalization',
	[65]: 'userLabel',
	[129]: 'valveConfigurationAndControl',
	[1283]: 'wakeOnLAN',
	[83]: 'laundryWasherControls',
	[148]: 'waterHeaterManagement',
	[158]: 'waterHeaterMode',
	[1363]: 'webRTCTransportProvider',
	[1364]: 'webRTCTransportRequestor',
	[54]: 'wiFiNetworkDiagnostics',
	[1105]: 'wiFiNetworkManagement',
	[258]: 'windowCovering',
	[1360]: 'zoneManagement',
}