# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish

on:
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: install libudev-dev
        run: sudo apt update; sudo apt-get install -y libudev-dev
      - name: setup git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - run: yarn
      - run: yarn tsc -b packages
      - name: publish updates
        run: yarn akala-automate-runner --loader @akala/automate-yamlloader --file @akala/semantic-release/publish.yml --verbose=silly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
